/* 읽는 법 사전 — java · shared/js/07-study.js 가 본문 인라인 코드의 탭별 첫 등장에 * 를 붙인다.
   [표기, 읽는 법, 실무에서 부르는 말·한 줄 뜻(선택)] — 표기는 코드에 나오는 그대로(대소문자 구분) */
window.LX_SAY = [
  /* ── 롬복 ── */
  ["@RequiredArgsConstructor", "리콰이어드 아그스 컨스트럭터", "롬복 — final 필드 생성자. 줄여서 '리콰이어드'"],
  ["@NoArgsConstructor", "노 아그스 컨스트럭터", "롬복 — 인자 없는 기본 생성자. '노아그'"],
  ["@AllArgsConstructor", "올 아그스 컨스트럭터", "롬복 — 모든 필드 생성자. '올아그'"],
  ["@Builder", "빌더", "롬복 — 빌더 패턴 자동 생성"],
  ["@Builder.Default", "빌더 닷 디폴트", "빌더에서 안 부른 필드의 기본값 유지"],
  ["@Value", "밸류", "롬복이면 불변 클래스, 스프링이면 설정값 주입"],
  ["@Data", "데이터", "롬복 — getter·setter·equals 등 한 번에"],
  ["@EqualsAndHashCode", "이퀄스 앤 해시코드", "equals·hashCode 자동 생성"],
  ["@EqualsAndHashCode.Include", "이퀄스 앤 해시코드 닷 인클루드", "비교에 넣을 필드 지정"],
  ["@ToString.Exclude", "투스트링 닷 익스클루드", "toString 에서 뺄 필드 — 순환 참조 차단"],
  ["@SneakyThrows", "스니키 스로우즈", "checked 예외를 선언 없이 던짐"],
  ["@With", "위드", "withXxx 복사 메서드 생성 — '위더'"],
  ["@NonNull", "논널 / 넌널", "null 이면 안 됨 — 롬복은 null 검사 삽입"],
  ["@Nullable", "널러블", "null 일 수 있음 표시"],
  ["@NullMarked", "널 마크드", "JSpecify — 이 범위는 기본 non-null"],
  ["@NullUnmarked", "널 언마크드", "NullMarked 범위에서 다시 해제"],
  ["onlyExplicitlyIncluded", "온리 익스플리시틀리 인클루디드", "Include 붙인 필드만 비교"],
  ["toBuilder", "투빌더", "기존 객체를 복사한 빌더"],

  /* ── 스프링 · 부트 ── */
  ["@Transactional", "트랜잭셔널", "트랜잭션 경계 — '트랜잭셔널 붙인다'"],
  ["@Transactional(readOnly = true)", "트랜잭셔널 리드온리 트루", "읽기 전용 트랜잭션"],
  ["readOnly = true", "리드온리 트루", "읽기 전용 — 더티 체킹 생략"],
  ["REQUIRES_NEW", "리콰이어스 뉴", "전파 옵션 — 항상 새 트랜잭션"],
  ["@ConfigurationProperties", "컨피규레이션 프로퍼티즈", "설정 묶음을 객체로 바인딩 — '컨피그 프로퍼티'"],
  ["@Configuration", "컨피규레이션", "빈 설정 클래스"],
  ["@ConditionalOnMissingBean", "컨디셔널 온 미싱 빈", "같은 빈이 없을 때만 등록"],
  ["@Async", "어싱크 / 에이싱크", "별도 스레드에서 비동기 실행"],
  ["@Cacheable", "캐셔블", "결과를 캐시에 저장·재사용"],
  ["@Scheduled", "스케줄드", "주기 실행 작업"],
  ["@Validated", "밸리데이티드", "검증 활성화 — 그룹·메서드 검증"],
  ["@Retryable", "리트라이어블", "실패 시 재시도"],
  ["@Lazy", "레이지", "빈을 처음 쓸 때 생성"],
  ["@PostConstruct", "포스트 컨스트럭트", "빈 생성·주입 직후 한 번 실행"],
  ["@EventListener", "이벤트 리스너", "스프링 이벤트 수신"],
  ["@RestControllerAdvice", "레스트 컨트롤러 어드바이스", "전역 예외 처리 — JSON 응답"],
  ["@ControllerAdvice", "컨트롤러 어드바이스", "전역 예외 처리"],
  ["@SpringBootTest", "스프링부트 테스트", "컨텍스트 전체를 띄우는 통합 테스트"],
  ["@DataJpaTest", "데이터 제이피에이 테스트", "JPA 계층만 띄우는 슬라이스 테스트"],
  ["@WebMvcTest", "웹 엠브이씨 테스트", "컨트롤러만 띄우는 슬라이스 테스트"],
  ["@MockitoBean", "모키토 빈", "@MockBean 의 후속 — 빈을 목으로 교체"],
  ["@MockBean", "목 빈", "빈을 목으로 교체(구버전)"],
  ["@SpyBean", "스파이 빈", "실제 빈을 감싸 일부만 가짜로"],
  ["@MockitoSpyBean", "모키토 스파이 빈", "@SpyBean 의 후속"],
  ["@JsonComponent", "제이슨 컴포넌트", "잭슨 직렬화기 등록(Boot 3)"],
  ["@JacksonComponent", "잭슨 컴포넌트", "@JsonComponent 의 후속(Boot 4)"],
  ["@JsonProperty", "제이슨 프로퍼티", "JSON 필드 이름 지정"],
  ["@JsonIgnore", "제이슨 이그노어", "JSON 에서 제외"],
  ["@JsonFormat", "제이슨 포맷", "날짜 등 JSON 표현 형식 지정"],
  ["@FunctionalInterface", "펑셔널 인터페이스", "추상 메서드 하나 — 람다 대상"],
  ["@Deprecated", "디프리케이티드", "지원 중단 예정 — '디프리케이트됐다'"],
  ["${}", "달러 중괄호", "플레이스홀더 · MyBatis 에선 문자열 치환(인젝션 위험)"],
  ["#{}", "샵 중괄호", "MyBatis 바인딩 파라미터 — 안전"],
  ["${value}", "달러 밸류", "문자열 그대로 치환 — SQL 인젝션 주의"],
  ["#{value}", "샵 밸류", "PreparedStatement 바인딩"],
  ["RestTemplate", "레스트 템플릿", "구형 동기 HTTP 클라이언트"],
  ["RestClient", "레스트 클라이언트", "RestTemplate 후속 동기 클라이언트"],
  ["JdbcTemplate", "제이디비씨 템플릿", "스프링 JDBC 헬퍼"],
  ["ObjectMapper", "오브젝트 매퍼", "잭슨 JSON 변환기"],
  ["JsonMapper", "제이슨 매퍼", "잭슨 3 의 ObjectMapper 후속"],
  ["graceful", "그레이스풀", "진행 중 요청을 끝내고 종료"],
  ["preStop", "프리스톱", "k8s — 종료 직전 훅"],

  /* ── JPA · QueryDSL · MyBatis ── */
  ["@ManyToOne", "매니 투 원", "다대일 연관 — '다대일'"],
  ["@OneToMany", "원 투 매니", "일대다 연관 — '일대다'"],
  ["LAZY", "레이지", "지연 로딩 — 'FetchType.LAZY'"],
  ["LazyInitializationException", "레이지 이니셜라이제이션 익셉션", "세션 밖 지연 로딩 실패 — '레이지 에러'"],
  ["@EntityGraph", "엔티티 그래프", "연관을 한 번에 페치 조인"],
  ["@Modifying", "모디파잉", "@Query 로 UPDATE·DELETE 할 때 필수"],
  ["@QueryProjection", "쿼리 프로젝션", "QueryDSL — DTO 생성자로 Q타입 생성"],
  ["@Enumerated(EnumType.STRING)", "이뉴머레이티드 이넘타입 스트링", "enum 을 이름 문자열로 저장"],
  ["@GeneratedValue", "제너레이티드 밸류", "PK 자동 생성"],
  ["@DiscriminatorColumn", "디스크리미네이터 컬럼", "상속 매핑에서 하위 타입 구분 컬럼"],
  ["ddl-auto", "디디엘 오토", "스키마 자동 생성 옵션"],
  ["default_batch_fetch_size", "디폴트 배치 페치 사이즈", "지연 로딩을 IN 절로 묶어 N+1 완화"],
  ["flush()", "플러시", "영속성 컨텍스트 변경을 DB 로 반영"],
  ["persist", "퍼시스트", "새 엔티티를 영속 상태로"],
  ["detach()", "디태치", "영속성 컨텍스트에서 분리"],
  ["cascade", "캐스케이드", "연관 엔티티에 작업 전파"],
  ["orphanRemoval", "오펀 리무벌", "고아 객체 자동 삭제"],
  ["fetchJoin()", "페치 조인", "연관을 한 쿼리로 함께 조회"],
  ["JPAQueryFactory", "제이피에이 쿼리 팩토리", "QueryDSL 쿼리 시작점"],
  ["QOrder", "큐오더", "QueryDSL 이 만든 Q타입"],
  ["Tuple", "튜플 / 터플", "여러 컬럼 묶음 결과"],
  ["map-underscore-to-camel-case", "맵 언더스코어 투 카멜 케이스", "user_name → userName 자동 매핑"],
  ["ROWNUM", "로우넘", "오라클·티베로 행 번호"],
  ["@Param", "파람", "MyBatis 파라미터 이름 지정"],
  ["javax.persistence", "자박스 퍼시스턴스", "구 JPA 패키지 — jakarta 로 바뀜"],
  ["jakarta", "자카르타", "javax 의 새 이름 — Jakarta EE"],
  ["javax", "자박스 / 자바엑스", "구 Java EE 패키지 접두사"],

  /* ── 시큐리티 ── */
  ["SecurityFilterChain", "시큐리티 필터 체인", "시큐리티 설정 빈"],
  ["AuthenticationEntryPoint", "오센티케이션 엔트리 포인트", "인증 실패(401) 처리기"],
  ["AccessDeniedHandler", "액세스 디나이드 핸들러", "인가 실패(403) 처리기"],
  ["AuthorizationManager", "오서라이제이션 매니저", "인가 판단기 — AccessDecisionManager 후속"],
  ["SecurityContextHolder", "시큐리티 컨텍스트 홀더", "현재 인증 정보 보관소"],
  ["ROLE_ADMIN", "롤 어드민", "ROLE_ 접두사가 붙은 권한 이름"],
  ["hasRole(\"ADMIN\")", "해즈 롤 어드민", "ROLE_ 을 자동으로 붙여 검사"],
  ["hasAuthority()", "해즈 오소리티", "권한 문자열 그대로 검사"],
  ["csrf.disable()", "씨서프 디스에이블", "CSRF 보호 끄기 — 씨서프 / 씨에스알에프"],
  ["SameSite", "세임사이트", "쿠키의 교차 사이트 전송 제한"],

  /* ── 언어 · 문법 ── */
  ["synchronized", "싱크로나이즈드", "모니터 락 — 한 번에 한 스레드만"],
  ["volatile", "볼라타일 / 볼러틸", "가시성 보장 — 캐시 말고 메모리에서 읽음"],
  ["sealed", "실드", "상속 가능한 하위 타입을 제한"],
  ["permits", "퍼밋츠", "sealed 의 허용 하위 타입 목록"],
  ["instanceof", "인스턴스오브", "타입 검사 — 패턴 매칭과 함께"],
  ["->", "화살표 / 애로우", "람다 · switch 화살표"],
  ["::", "더블 콜론", "메서드 레퍼런스 — '메서드 참조'"],
  ["\"\"\"", "트리플 쿼트", "텍스트 블록 — 여러 줄 문자열"],
  ["==", "이퀄 이퀄", "참조 비교 — 값 비교는 equals"],
  ["invokedynamic", "인보크다이내믹", "람다가 쓰는 바이트코드 — '인디'"],
  ["LambdaMetafactory", "람다 메타팩토리", "람다 객체를 런타임에 만드는 곳"],
  ["invokeExact", "인보크 이그잭트", "MethodHandle 정확한 시그니처 호출"],
  ["Callable", "콜러블", "값을 돌려주는 작업"],
  ["Runnable", "러너블", "값 없는 작업"],
  ["Predicate", "프레디케이트", "참·거짓 판단 함수"],
  ["Supplier", "서플라이어", "인자 없이 값을 주는 함수"],
  ["Comparator", "컴퍼레이터", "정렬 비교 기준"],
  ["UnaryOperator<T>", "유너리 오퍼레이터", "T → T 함수"],
  ["BinaryOperator<T>", "바이너리 오퍼레이터", "(T, T) → T 함수"],
  ["BiFunction<T,U,R>", "바이 펑션", "인자 두 개 함수"],
  ["orElseGet", "오얼엘스 겟", "비었을 때만 함수 실행"],
  ["orElse", "오얼엘스", "비었을 때 기본값 — 인자는 항상 계산됨"],
  ["orElseThrow()", "오얼엘스 스로우", "비었으면 예외"],
  ["ifPresentOrElse", "이프 프레즌트 오얼엘스", "있으면 A, 없으면 B"],
  ["computeIfAbsent", "컴퓨트 이프 앱선트", "키가 없을 때만 계산해 넣음"],
  ["parallelStream", "패럴렐 스트림", "병렬 스트림 — 공용 풀 사용"],
  ["flatMap", "플랫맵", "펼쳐서 하나로 이어 붙임"],
  ["peek", "픽", "중간에 엿보기 — 디버깅용"],
  ["reversed()", "리버스드", "역순 뷰"],
  ["SequencedCollection", "시퀀스드 컬렉션", "순서 있는 컬렉션 공통 인터페이스"],
  ["mapConcurrent", "맵 컨커런트", "Gatherers — 가상 스레드로 동시 매핑"],
  ["O(n²)", "빅오 엔 제곱", "입력 제곱에 비례하는 시간"],
  ["finalize()", "파이널라이즈", "폐기된 종료자 — Cleaner 로 대체"],
  ["ArrayDeque", "어레이 덱", "Stack 대신 쓰는 양방향 큐"],

  /* ── 동시성 ── */
  ["CompletableFuture", "컴플리터블 퓨처", "비동기 결과 조합 — 'CF'"],
  ["ConcurrentHashMap", "컨커런트 해시맵", "스레드 안전 맵 — 'CHM'"],
  ["ExecutorService", "익스큐터 서비스 / 이그제큐터 서비스", "스레드 풀"],
  ["ThreadLocal", "스레드 로컬", "스레드마다 따로 갖는 변수"],
  ["ScopedValue", "스코프드 밸류", "ThreadLocal 의 불변·범위 한정 대안"],
  ["StructuredTaskScope", "스트럭처드 태스크 스코프", "구조적 동시성 — 묶어서 시작·종료"],
  ["AtomicInteger", "아토믹 인티저", "락 없는 원자적 정수"],
  ["CopyOnWriteArrayList", "카피 온 라이트 어레이리스트", "쓸 때 복사 — 읽기 많은 목록"],
  ["ReentrantLock", "리엔트런트 락", "재진입 가능한 명시적 락"],
  ["ForkJoinPool.commonPool", "포크조인풀 커먼풀", "병렬 스트림·CF 기본 풀"],
  ["newVirtualThreadPerTaskExecutor()", "뉴 버추얼 스레드 퍼 태스크 익스큐터", "작업마다 가상 스레드"],
  ["TaskDecorator", "태스크 데코레이터", "@Async 작업에 MDC 등 전달"],

  /* ── 리액티브 · 네티 ── */
  ["Flux", "플럭스", "0~N개 비동기 스트림"],
  [".block()", "블록", "리액티브를 동기로 기다림 — 이벤트 루프에서 금지"],
  ["subscribe()", "섭스크라이브", "구독 — 이때 실제 실행"],
  ["boundedElastic", "바운디드 일래스틱", "블로킹 작업용 스케줄러"],
  ["publishOn", "퍼블리시온", "이후 연산을 다른 스케줄러로"],
  ["contextWrite", "컨텍스트 라이트", "리액터 Context 에 값 넣기"],
  ["ByteBuf", "바이트버프", "네티 버퍼 — release 필수"],
  ["BlockHound", "블록하운드", "이벤트 루프 블로킹 감지 도구"],

  /* ── 빌드 · JDK 도구 · JVM ── */
  ["./gradlew", "그래들 래퍼 / 그래들W", "프로젝트에 고정된 Gradle 실행"],
  ["./mvnw", "메이븐 래퍼", "프로젝트에 고정된 Maven 실행"],
  ["javac", "자바씨", "자바 컴파일러"],
  ["jlink", "제이링크", "필요한 모듈만 담은 런타임 생성"],
  ["jpackage", "제이패키지", "설치 파일(exe·msi) 생성"],
  ["jshell", "제이쉘", "자바 REPL"],
  ["jcmd", "제이커맨드 / 제이씨엠디", "실행 중 JVM 진단 만능 도구"],
  ["jstack", "제이스택", "스레드 덤프"],
  ["jmap", "제이맵", "힙 정보·덤프"],
  ["keytool", "키툴", "인증서·키스토어 관리"],
  ["JAVA_HOME", "자바 홈", "JDK 설치 경로 환경 변수"],
  ["-Xmx", "엑스엠엑스", "최대 힙 크기"],
  ["-Xms", "엑스엠에스", "시작 힙 크기"],
  ["MaxRAMPercentage", "맥스 램 퍼센티지", "컨테이너 메모리 대비 힙 비율"],
  ["HeapDumpOnOutOfMemoryError", "힙덤프 온 아웃오브메모리 에러", "OOM 때 힙 덤프 자동 저장"],
  ["Metaspace", "메타스페이스", "클래스 메타데이터 영역"],
  ["OutOfMemoryError", "아웃 오브 메모리 에러", "'OOM(오오엠)'"],
  ["StackOverflowError", "스택 오버플로 에러", "재귀·순환 참조로 스택 초과"],
  ["NullPointerException", "널 포인터 익셉션", "'NPE(엔피이)'"],
  ["NoClassDefFoundError", "노 클래스 데프 파운드 에러", "컴파일 땐 있던 클래스가 런타임에 없음"],
  ["NoSuchMethodError", "노 서치 메서드 에러", "라이브러리 버전 충돌의 대표 증상"],
  ["ClassNotFoundException", "클래스 낫 파운드 익셉션", "'CNFE' — 클래스패스에 없음"],
  ["--add-opens", "애드 오픈스", "모듈 내부를 리플렉션에 열어 줌"],
  ["--enable-preview", "이네이블 프리뷰", "미리보기 기능 켜기"],
  ["-XX:AOTCache", "에이오티 캐시", "기동 가속용 AOT 캐시"],
  ["sun.misc.Unsafe", "썬 미스크 언세이프", "JDK 내부 저수준 API — 퇴출 중"],
  ["module-info.java", "모듈 인포", "모듈 선언 파일"],
  ["package-info.java", "패키지 인포", "패키지 단위 어노테이션 파일"],
  ["BOOT-INF/lib", "부트 인프 립", "부트 실행 jar 안 의존성 폴더"],
  ["Arena", "아레나", "FFM — 네이티브 메모리 수명 관리"],
  ["MemorySegment", "메모리 세그먼트", "FFM — 네이티브 메모리 조각"],

  /* ── 로깅 · 관측 ── */
  ["SLF4J", "에스엘에프포제이", "로깅 퍼사드 — 구현체는 따로"],
  ["log4j-core", "로그포제이 코어", "Log4j2 구현체"],
  ["log4j-to-slf4j", "로그포제이 투 에스엘에프포제이", "Log4j API 호출을 SLF4J 로 넘김"],
  ["jul-to-slf4j", "제이유엘 투 에스엘에프포제이", "java.util.logging 을 SLF4J 로"],
  ["java.util.logging", "자바 유틸 로깅", "'JUL(제이유엘)'"],
  ["commons-logging", "커먼즈 로깅", "'JCL' — 아파치 로깅 퍼사드"],
  ["reload4j", "리로드포제이", "log4j 1.x 보안 패치 포크"],
  ["logback-spring.xml", "로그백 스프링 엑스엠엘", "스프링 프로필을 쓰는 로그백 설정"],
  ["AsyncAppender", "어싱크 어펜더", "로그를 큐에 넣고 별도 스레드가 기록"],
  ["additivity", "애디티비티", "상위 로거로 로그 전파 여부"],
  ["MDC.clear()", "엠디씨 클리어", "스레드별 로그 컨텍스트 비우기"],
  ["traceId", "트레이스 아이디", "요청 하나를 잇는 추적 ID"],
  ["spanId", "스팬 아이디", "추적 안의 구간 ID"],
  ["traceparent", "트레이스페어런트", "W3C 추적 헤더"],
  ["p6spy-spring-boot-starter", "피식스스파이", "실제 바인딩된 SQL 로그"],

  /* ── 기타 ── */
  ["Platform.runLater", "플랫폼 런레이터", "JavaFX UI 스레드에서 실행"],
  ["bindBidirectional", "바인드 바이디렉셔널", "양방향 바인딩"],
  ["MS949", "엠에스 구사구", "윈도우 한글 인코딩 — CP949"],
  ["chcp 65001", "씨에이치씨피 육오공공일", "콘솔 코드페이지를 UTF-8 로"],
  ["EF BB BF", "봄(BOM)", "UTF-8 BOM 바이트"],
  [".proto", "프로토", "gRPC 프로토콜 버퍼 정의 파일"],
  ["@GrpcService", "지알피씨 서비스", "gRPC 서버 구현 등록"],
  ["max.poll.interval.ms", "맥스 폴 인터벌", "카프카 — poll 사이 최대 간격"],
  ["bootstrap-servers", "부트스트랩 서버스", "카프카 — 처음 접속할 브로커 목록"],
  ["FeignClient", "페인 클라이언트", "선언형 HTTP 클라이언트 — '페인'"],

  /* ── 추가: 본문 인라인 토큰 ── */
  ["var", "바", "지역 변수 타입 추론"],
  ["@Autowired", "오토와이어드", "의존성 주입 지점 표시"],
  ["@Qualifier", "퀄리파이어", "같은 타입 빈 중 하나를 이름으로 지정"],
  ["@Version", "버전", "낙관적 락 버전 컬럼"],
  ["staticName", "스태틱 네임", "롬복 — 정적 팩토리 이름 지정"],
  ["-parameters", "파라미터스", "파라미터 이름을 바이트코드에 남기는 컴파일 옵션"],
  ["Serializable", "시리얼라이저블", "직렬화 가능 표시 인터페이스"],
  ["BigDecimal", "빅데시멀", "돈 계산용 정확한 소수"],
  ["try-with-resources", "트라이 위드 리소시즈", "자동 close — '트라이 위드 리소스'"],
  ["thenApply", "덴 어플라이", "CF 결과를 변환"],
  ["supplyAsync", "서플라이 어싱크", "값을 돌려주는 비동기 작업 시작"],
  ["tryLock", "트라이 락", "기다리지 않고(또는 시간 제한) 락 시도"],
  ["park", "파크", "스레드를 멈춰 세움 — 덤프의 'parking'"],
  ["LinkedBlockingQueue", "링크드 블로킹 큐", "기본 무제한 큐 — 풀 큐로 쓰면 OOM 위험"],
  ["setAccessible(true)", "셋 액세서블 트루", "리플렉션으로 private 접근"],
  ["Hibernate.unproxy()", "하이버네이트 언프록시", "프록시를 실제 엔티티로"],
  ["open-in-view", "오픈 인 뷰", "'OSIV(오시브)' — 뷰까지 영속성 컨텍스트 유지"],
  ["leak-detection-threshold", "릭 디텍션 스레숄드", "Hikari — 커넥션 누수 감지 시간"],
  ["resultType", "리절트 타입", "MyBatis 결과 매핑 타입"],
  ["WebClient", "웹클라이언트", "리액티브 HTTP 클라이언트"],
  ["JdbcClient", "제이디비씨 클라이언트", "JdbcTemplate 의 유창한 후속 API"],
  ["r2dbc", "알투디비씨", "리액티브 DB 드라이버 규격"],
  ["PARANOID", "패러노이드", "네티 누수 감지 최고 단계"],
  ["io_uring", "아이오 유링", "리눅스 비동기 I/O 인터페이스"],
  ["tools.jackson", "툴즈 잭슨", "잭슨 3 패키지"],
  ["com.fasterxml", "컴 패스터엑스엠엘", "잭슨 2 패키지"],
  ["FAIL_ON_UNKNOWN_PROPERTIES", "페일 온 언노운 프로퍼티즈", "모르는 JSON 필드면 실패하는 옵션"],
  ["mapstruct", "맵스트럭트", "컴파일 타임 DTO 매퍼"],
  ["springdoc-openapi", "스프링독 오픈에이피아이", "Swagger UI 자동 생성"],
  ["jakarta.xml.bind", "자카르타 엑스엠엘 바인드", "'JAXB(잭스비)' — XML 바인딩"],
  ["WebSecurityConfigurerAdapter", "웹 시큐리티 컨피규어러 어댑터", "구 시큐리티 설정 방식 — 제거됨"],
  ["authorizeHttpRequests()", "오서라이즈 HTTP 리퀘스츠", "URL 별 인가 규칙"],
  ["requestMatchers", "리퀘스트 매처스", "인가 규칙을 걸 URL 패턴"],
  ["-XX:+UseZGC", "유즈 제트지씨", "ZGC 사용 — '제트지씨 / 지지씨'"],
  ["NativeMemoryTracking", "네이티브 메모리 트래킹", "'NMT' — 힙 밖 메모리 추적"],
  ["SIGKILL", "시그킬", "강제 종료 신호 — kill -9"],
  ["log4j", "로그포제이", "아파치 로깅 라이브러리"],
  ["jps", "제이피에스", "실행 중 자바 프로세스 목록"],
  ["jdeps", "제이뎁스", "클래스·모듈 의존성 분석"],
  ["temurin", "테무린", "Adoptium 의 OpenJDK 배포판"],
  ["PKIX", "피킥스", "인증서 경로 검증 실패 오류에 나오는 말"],
  ["changeit", "체인지잇", "cacerts 기본 비밀번호"],
  ["psvm", "피에스브이엠", "IntelliJ main 메서드 단축 입력"],
];
