/* 읽는 법 사전 — csharp · shared/js/07-study.js 가 본문 인라인 코드의 탭별 첫 등장에 * 를 붙인다.
   [표기, 읽는 법, 실무에서 부르는 말·한 줄 뜻(선택)] — 표기는 코드에 나오는 그대로(대소문자 구분) */
window.LX_SAY = [
  /* ── 언어 · 문법 ── */
  ["async", "어싱크 / 에이싱크", "비동기 메서드 표시 — '어싱크 메서드'"],
  ["await", "어웨잇", "작업이 끝날 때까지 스레드를 놓고 기다림"],
  ["async void", "어싱크 보이드", "기다릴 수 없는 비동기 — 이벤트 핸들러 말고는 금지"],
  ["=>", "람다 화살표 / 고즈 투", "람다식·식 본문 멤버 — '화살표'"],
  ["?.", "널 조건 연산자", "앞이 null 이면 null 을 돌려줌 — '물음표 점'"],
  ["??", "널 병합 연산자", "왼쪽이 null 이면 오른쪽 값 — '물음표 두 개'"],
  ["??=", "널 병합 할당", "null 일 때만 대입"],
  ["var", "바", "타입 추론 지역 변수"],
  ["using", "유징", "네임스페이스 가져오기 · 끝나면 Dispose 자동 호출"],
  ["lock", "락", "한 번에 한 스레드만 들어오게 잠금"],
  ["struct", "스트럭트", "값 형식 — 복사로 전달"],
  ["readonly struct", "리드온리 스트럭트", "필드를 못 바꾸는 값 형식 — 방어적 복사 없음"],
  ["readonly", "리드온리", "생성 뒤 바꿀 수 없는 필드"],
  ["record", "레코드", "값 비교·불변 데이터 형식"],
  ["partial", "파셜", "클래스를 여러 파일로 나눠 정의 — 소스 생성기와 짝"],
  ["sealed", "실드", "상속 금지"],
  ["virtual", "버추얼", "하위 클래스가 재정의할 수 있는 멤버"],
  ["delegate", "델리게이트", "메서드를 담는 형식 — 함수 포인터 자리"],
  ["switch", "스위치", "분기 — C# 은 switch 식·패턴까지"],
  ["foreach", "포이치", "컬렉션을 하나씩 도는 반복문"],
  ["yield return", "일드 리턴", "값을 하나씩 내주는 반복기 — 유니티 코루틴도 이것"],
  ["stackalloc", "스택얼록", "스택에 배열 할당 — Span 과 짝"],
  ["required", "리콰이어드", "초기화 때 반드시 넣어야 하는 멤버"],
  ["Nullable", "널러블", "null 허용 — 값 형식이면 Nullable<T>"],
  ["Nullable<T>", "널러블 오브 티", "int? 의 정식 이름"],
  ["decimal", "데시멀", "10진 실수 — 돈 계산용"],
  ["Func", "펑크", "값을 돌려주는 델리게이트"],
  ["Action", "액션", "C# — 돌려주는 값이 없는 델리게이트 형식"],
  ["try/catch", "트라이 캐치", "예외 잡기"],
  ["NullReferenceException", "널 레퍼런스 익셉션", "null 을 건드림 — 줄여서 'NRE · 널레퍼'"],
  ["InvalidOperationException", "인밸리드 오퍼레이션 익셉션", "지금 상태에서는 못 하는 호출"],
  ["StringBuilder", "스트링빌더", "문자열 이어 붙이기용 버퍼"],
  ["DateTime.Now", "데이트타임 나우", "지역 시각 — 서버에서는 UtcNow 권장"],
  ["DateTimeOffset.UtcNow", "데이트타임오프셋 유티씨나우", "오프셋 포함 UTC 현재 시각"],
  ["TimeProvider", "타임 프로바이더", "시계를 주입받는 추상화 — 테스트에서 시간 고정"],
  ["Random.Shared", "랜덤 닷 셰어드", "스레드 안전 공용 난수기"],

  /* ── 컬렉션 · LINQ ── */
  ["List<T>", "리스트 오브 티", "가변 길이 배열"],
  ["Queue<T>", "큐 오브 티", "먼저 넣은 것이 먼저 — FIFO"],
  ["Stack<T>", "스택 오브 티", "나중에 넣은 것이 먼저 — LIFO"],
  ["LinkedList<T>", "링크드 리스트", "이중 연결 리스트"],
  ["PriorityQueue", "프라이오리티 큐", "우선순위 큐 — 힙"],
  ["ConcurrentQueue<T>", "컨커런트 큐", "잠금 없이 여러 스레드가 쓰는 큐"],
  ["Dictionary", "딕셔너리", "키-값 해시 맵 — '딕트'"],
  ["Enqueue", "인큐", "큐 뒤에 넣기"],
  ["Dequeue()", "디큐", "큐 앞에서 꺼내기"],
  ["TryDequeue", "트라이 디큐", "비었으면 false — 예외 없음"],
  ["Peek()", "피크", "꺼내지 않고 앞만 보기"],
  ["IEnumerable<T>", "아이 이뉴머러블 오브 티", "foreach 로 돌 수 있는 시퀀스"],
  ["IQueryable", "아이 쿼리어블", "식 트리로 DB 쿼리가 되는 시퀀스"],
  ["IAsyncEnumerable", "아이 어싱크 이뉴머러블", "await foreach 로 도는 비동기 시퀀스"],
  ["IAsyncEnumerable<T>", "아이 어싱크 이뉴머러블 오브 티", "await foreach 로 도는 비동기 시퀀스"],
  ["Where", "웨어", "LINQ 거르기"],
  ["Select", "셀렉트", "LINQ 변환(map)"],
  ["ToList()", "투리스트", "지연 실행을 끝내고 리스트로 확정"],
  ["OrderBy", "오더바이", "LINQ 정렬"],

  /* ── 비동기 · 동시성 ── */
  ["Task", "태스크", "비동기 작업 하나 — 자바 Future 자리"],
  ["Task<T>", "태스크 오브 티", "값을 돌려주는 비동기 작업"],
  ["ValueTask", "밸류 태스크", "자주 동기로 끝나는 경로용 가벼운 Task"],
  ["Task.Run", "태스크 런", "스레드 풀에 작업 던지기"],
  ["Task.Delay", "태스크 딜레이", "스레드를 막지 않는 대기"],
  ["Task.WhenAll", "태스크 웬올", "여러 작업을 동시에 기다림"],
  [".Result", "닷 리절트", "Task 결과를 막고 기다림 — 데드락 원인"],
  [".Wait()", "닷 웨잇", "Task 를 막고 기다림 — sync-over-async"],
  ["CancellationToken", "캔슬레이션 토큰", "취소 신호 — 줄여서 'ct'"],
  ["SemaphoreSlim", "세마포어 슬림", "동시 실행 수 제한 — await 가능"],
  ["Mutex", "뮤텍스", "프로세스 간에도 쓰는 잠금"],
  ["Interlocked", "인터락드", "원자적 증감·교환"],
  ["volatile", "볼라타일", "캐시하지 말고 매번 메모리에서 읽기"],
  ["PeriodicTimer", "피리오딕 타이머", "await 로 도는 주기 타이머"],
  ["Parallel.ForEachAsync", "패러렐 포이치 어싱크", "동시 개수를 정해 병렬 비동기 반복"],
  ["Channel<T>", "채널 오브 티", "생산자-소비자 비동기 큐"],
  ["Channel.CreateBounded", "채널 크리에이트 바운디드", "크기 제한 채널 — 가득 차면 대기·버림"],
  ["DropOldest", "드롭 올디스트", "가득 차면 가장 오래된 것 버리기"],
  ["Writer.Complete()", "라이터 컴플리트", "더 쓸 것 없음 — 소비자 루프 종료 신호"],
  ["Thread.Sleep", "스레드 슬립", "스레드를 막고 대기 — 비동기에서는 금지"],

  /* ── 메모리 · 성능 · 인터롭 ── */
  ["Span<T>", "스팬 오브 티", "배열 일부를 복사 없이 가리키는 창"],
  ["Span", "스팬", "복사 없는 메모리 조각"],
  ["ReadOnlySpan<T>", "리드온리 스팬", "읽기 전용 Span"],
  ["Memory<T>", "메모리 오브 티", "힙에 둘 수 있는 Span — await 너머로 전달"],
  ["ArrayPool<T>", "어레이 풀", "배열을 빌려 쓰고 돌려주기 — Rent/Return"],
  ["ArrayPool", "어레이 풀", "배열 재사용 풀"],
  ["IDisposable", "아이 디스포저블", "Dispose 로 자원 해제하는 형식"],
  ["Dispose", "디스포즈", "자원 해제 — using 이 자동 호출"],
  ["DllImport", "디엘엘 임포트", "네이티브 함수 선언(P/Invoke)"],
  ["[UnmanagedCallersOnly]", "언매니지드 콜러스 온리", "네이티브에서 부를 수 있는 C# 함수"],
  ["[StructLayout(LayoutKind.Sequential)]", "스트럭트 레이아웃 시퀀셜", "필드를 선언 순서대로 배치 — C 구조체와 맞춤"],
  ["GC.Collect", "지씨 콜렉트", "GC 강제 실행 — 보통 쓰지 않음"],
  ["InvariantGlobalization", "인베리언트 글로벌라이제이션", "ICU 없이 문화권 고정 — 컨테이너 용량 절약"],
  ["DOTNET_gcServer=1", "닷넷 지씨서버 일", "서버 GC 켜기"],
  ["gcroot", "지씨루트", "dotnet-dump — 객체를 붙잡은 루트 추적"],
  ["dumpheap -stat", "덤프힙 스탯", "힙에 쌓인 형식별 개수·크기"],

  /* ── .NET 도구 · 프로젝트 ── */
  ["dotnet", "닷넷", ".NET CLI"],
  [".NET", "닷넷", "마이크로소프트 런타임·SDK"],
  ["dotnet run", "닷넷 런", "빌드하고 실행"],
  ["dotnet build", "닷넷 빌드", "빌드만"],
  ["dotnet publish", "닷넷 퍼블리시", "배포용 산출물 만들기"],
  ["dotnet test", "닷넷 테스트", "테스트 실행"],
  ["dotnet format", "닷넷 포맷", "코드 스타일 자동 정리"],
  ["dotnet ef", "닷넷 이에프", "EF Core 마이그레이션 도구"],
  ["dotnet --info", "닷넷 대시대시 인포", "설치된 SDK·런타임 확인"],
  ["dotnet-counters", "닷넷 카운터스", "실시간 런타임 지표 보기"],
  ["dotnet-dump", "닷넷 덤프", "프로세스 메모리 덤프 수집·분석"],
  ["dotnet-trace", "닷넷 트레이스", "CPU·이벤트 추적 수집"],
  ["dotnet-gcdump", "닷넷 지씨덤프", "GC 힙 스냅숏"],
  [".csproj", "씨에스프로젝트 / 씨에스프로즈", "C# 프로젝트 파일"],
  [".sln", "에스엘엔 / 솔루션 파일", "솔루션 파일"],
  [".slnx", "에스엘엔엑스", "XML 형식 새 솔루션 파일"],
  ["Program.cs", "프로그램 닷 씨에스", "앱 시작점 파일"],
  ["global.json", "글로벌 제이슨", "쓸 SDK 버전 고정"],
  ["appsettings.json", "앱세팅스 제이슨", "설정 파일"],
  ["launchSettings.json", "론치세팅스 제이슨", "로컬 실행 프로필(포트·환경)"],
  ["Directory.Build.props", "디렉터리 빌드 프롭스", "하위 프로젝트 공통 MSBuild 설정"],
  ["Directory.Packages.props", "디렉터리 패키지스 프롭스", "중앙 패키지 버전 관리(CPM)"],
  ["NuGet.Config", "누겟 컨피그", "패키지 원본 설정"],
  [".editorconfig", "에디터컨피그", "코드 스타일 규칙 파일"],
  ["TreatWarningsAsErrors", "트리트 워닝스 애즈 에러스", "경고를 오류로 — 빌드 실패"],
  ["TargetFramework", "타깃 프레임워크", "빌드 대상 .NET 버전(net10.0 등)"],
  ["net10.0", "넷 텐 닷 제로", ".NET 10 대상 이름(TFM)"],
  ["netstandard2.0", "넷스탠더드 이 점 영", "구·신 .NET 공용 라이브러리 대상"],
  ["ASPNETCORE_ENVIRONMENT", "에이에스피닷넷코어 인바이런먼트", "실행 환경 이름(Development·Production)"],
  ["ASPNETCORE_URLS", "에이에스피닷넷코어 유알엘스", "듣는 주소 지정"],
  ["Serilog", "세리로그", "구조화 로깅 라이브러리"],
  ["nlog.config", "엔로그 컨피그", "NLog 설정 파일"],
  ["NSubstitute", "엔서브스티튜트", "목 객체 라이브러리"],

  /* ── ASP.NET Core · 호스팅 ── */
  ["HttpClient", "에이치티티피 클라이언트", "HTTP 호출 — 매번 new 하면 소켓 고갈"],
  ["new HttpClient()", "뉴 에이치티티피 클라이언트", "직접 생성 — 소켓 고갈 원인"],
  ["IHttpClientFactory", "아이 에이치티티피 클라이언트 팩토리", "HttpClient 를 풀링해 주는 팩토리"],
  ["ILogger<T>", "아이로거 오브 티", "카테고리가 붙은 로거"],
  ["ILogger", "아이로거", "로깅 추상화"],
  ["[LoggerMessage]", "로거 메시지", "소스 생성 고성능 로그 메서드"],
  ["BeginScope", "비긴 스코프", "로그에 공통 속성 묶기"],
  ["BackgroundService", "백그라운드 서비스", "호스트와 함께 도는 장기 작업"],
  ["IHostedService", "아이 호스티드 서비스", "시작·종료를 받는 호스트 작업"],
  ["IOptions<T>", "아이옵션스 오브 티", "설정 바인딩 — 시작 때 한 번"],
  ["IOptionsMonitor<T>", "아이옵션스 모니터", "설정이 바뀌면 다시 읽음"],
  ["ValidateOnStart", "밸리데이트 온 스타트", "시작 때 설정 검증 — 잘못되면 바로 죽음"],
  ["ProblemDetails", "프라블럼 디테일스", "표준 오류 응답 형식(RFC 9457)"],
  ["Kestrel", "케스트럴", "ASP.NET Core 내장 웹 서버"],
  ["web.config", "웹 컨피그", "IIS 설정 파일"],
  ["app_offline.htm", "앱 오프라인", "IIS 앱을 잠시 내리는 파일"],
  ["UseForwardedHeaders", "유즈 포워디드 헤더스", "프록시가 붙인 X-Forwarded-* 반영"],
  ["X-Forwarded-For", "엑스 포워디드 포", "원래 클라이언트 IP 헤더"],
  ["WebApplicationFactory<Program>", "웹 애플리케이션 팩토리", "메모리 안에 앱을 띄우는 통합 테스트"],
  ["MemoryCache", "메모리 캐시", "프로세스 메모리 캐시"],
  ["ExecStart", "엑섹 스타트", "systemd — 실행 명령"],
  ["client_max_body_size", "클라이언트 맥스 바디 사이즈", "nginx 업로드 크기 제한"],
  ["sp_getapplock", "에스피 겟앱락", "SQL Server 애플리케이션 잠금 — 중복 실행 방지"],
  ["FOR UPDATE SKIP LOCKED", "포 업데이트 스킵 락드", "잠긴 행은 건너뛰고 가져오기 — 작업 큐"],

  /* ── EF Core · 데이터 ── */
  ["DbContext", "디비 컨텍스트", "EF Core 작업 단위"],
  ["DbSet<T>", "디비셋 오브 티", "테이블에 대응하는 컬렉션"],
  ["SaveChanges", "세이브 체인지스", "추적한 변경을 DB 에 반영"],
  ["AsNoTracking", "애즈 노트래킹", "추적 끄고 읽기 — 조회 전용"],
  ["AsSplitQuery", "애즈 스플릿 쿼리", "Include 를 여러 쿼리로 나눠 카티션 폭발 방지"],
  ["Include", "인클루드", "EF Core — 연관 엔티티 함께 로드 · csproj 에선 포함할 파일"],
  ["ExecuteUpdate", "익스큐트 업데이트", "엔티티 안 읽고 일괄 UPDATE"],
  ["ExecuteDelete", "익스큐트 딜리트", "엔티티 안 읽고 일괄 DELETE"],
  ["IDbContextFactory", "아이 디비컨텍스트 팩토리", "필요할 때 DbContext 새로 만들기"],
  ["RowVersion", "로우버전", "낙관적 동시성 토큰"],
  ["TransactionScope", "트랜잭션 스코프", "블록 단위 앰비언트 트랜잭션"],
  ["SqlBulkCopy", "에스큐엘 벌크 카피", "SQL Server 대량 적재"],
  ["EF Core", "이에프 코어", "Entity Framework Core — ORM"],

  /* ── Blazor ── */
  [".razor", "닷 레이저", "Blazor 컴포넌트 파일"],
  ["_Imports.razor", "임포츠 레이저", "폴더 공통 using"],
  ["@rendermode", "렌더모드", "컴포넌트 렌더 방식(서버·WASM·자동)"],
  ["[Parameter]", "파라미터", "부모가 넘기는 컴포넌트 속성"],
  ["EventCallback", "이벤트 콜백", "자식→부모 이벤트"],
  ["StateHasChanged()", "스테이트 해즈 체인지드", "다시 그려 달라는 요청"],
  ["InvokeAsync(StateHasChanged)", "인보크 어싱크 스테이트 해즈 체인지드", "다른 스레드에서 안전하게 다시 그리기"],
  ["@key", "앳 키", "목록 항목 식별 — 재사용 방지"],
  ["Virtualize", "버추얼라이즈", "보이는 행만 그리는 가상화"],
  ["IJSRuntime", "아이 제이에스 런타임", "JS 함수 호출 통로"],
  ["RenderFragment<T>", "렌더 프래그먼트 오브 티", "넘겨받는 UI 조각"],
  ["OnAfterRenderAsync", "온 애프터 렌더 어싱크", "렌더 뒤 훅 — JS 호출은 여기서"],
  ["DotNetObjectReference", "닷넷 오브젝트 레퍼런스", "JS 가 .NET 메서드를 부르도록 넘기는 참조"],
  ["AuthenticationStateProvider", "어센티케이션 스테이트 프로바이더", "현재 로그인 상태 공급자"],
  [".wasm", "와즘", "WebAssembly 바이너리"],
  ["[Authorize]", "어소라이즈", "인증·권한 필요"],
  ["[Required]", "리콰이어드", "필수 값 검증"],

  /* ── 유니티 ── */
  ["MonoBehaviour", "모노비헤이비어", "유니티 스크립트 기본 클래스"],
  ["Awake", "어웨이크", "생성 직후 한 번 — Start 보다 먼저"],
  ["Start", "스타트", "첫 프레임 전에 한 번"],
  ["Update()", "업데이트", "매 프레임 호출"],
  ["Update", "업데이트", "유니티 — 매 프레임 호출 · csproj 에선 기존 항목 속성 바꾸기"],
  ["FixedUpdate", "픽스드 업데이트", "고정 간격 물리 갱신"],
  ["LateUpdate", "레이트 업데이트", "모든 Update 뒤 — 카메라 추적"],
  ["OnEnable", "온 이네이블", "켜질 때마다"],
  ["OnDisable", "온 디서블", "꺼질 때마다 — 구독 해제 자리"],
  ["OnDestroy", "온 디스트로이", "파괴 직전"],
  ["GetComponent", "겟컴포넌트", "같은 오브젝트의 컴포넌트 찾기 — 캐싱 권장"],
  ["Instantiate", "인스턴시에이트", "프리팹 복제 생성"],
  ["Destroy", "디스트로이", "오브젝트 파괴"],
  ["SetActive(false)", "셋액티브 폴스", "오브젝트 끄기"],
  ["Time.deltaTime", "타임 델타타임", "지난 프레임 걸린 시간 — 이동량에 곱함"],
  ["Time.timeScale", "타임 타임스케일", "게임 시간 배속 — 0 이면 일시정지"],
  ["unscaledDeltaTime", "언스케일드 델타타임", "timeScale 영향 없는 델타타임"],
  ["transform.position", "트랜스폼 포지션", "월드 좌표 위치"],
  ["Vector3", "벡터 쓰리", "3차원 벡터"],
  ["Quaternion", "쿼터니언", "회전 표현"],
  ["Mathf", "매스 에프", "유니티 float 수학 함수"],
  ["ScriptableObject", "스크립터블 오브젝트", "에셋으로 저장하는 데이터 객체 — 'SO'"],
  ["[SerializeField]", "시리얼라이즈 필드", "private 필드를 인스펙터에 노출"],
  ["[SerializeReference]", "시리얼라이즈 레퍼런스", "인터페이스·다형 필드를 직렬화"],
  ["StartCoroutine", "스타트 코루틴", "코루틴 시작"],
  ["WaitForSeconds", "웨잇 포 세컨즈", "코루틴 대기 — timeScale 영향 받음"],
  ["WaitForSecondsRealtime", "웨잇 포 세컨즈 리얼타임", "실제 시간 기준 대기"],
  ["Awaitable", "어웨이터블", "유니티 6 의 await 대기 형식"],
  ["Debug.Log", "디버그 로그", "콘솔 출력"],
  ["Rigidbody2D", "리지드바디 투디", "2D 물리 몸체"],
  ["PlayerPrefs", "플레이어 프렙스", "간단한 키-값 저장소"],
  ["SpriteRenderer", "스프라이트 렌더러", "2D 이미지 그리기"],
  ["Camera.main", "카메라 메인", "MainCamera 태그 카메라"],
  ["NativeArray", "네이티브 어레이", "GC 밖 메모리 배열 — 잡 시스템용"],
  ["MaterialPropertyBlock", "머티리얼 프로퍼티 블록", "머티리얼 복제 없이 개별 속성 바꾸기"],
  ["link.xml", "링크 엑스엠엘", "IL2CPP 코드 제거에서 지킬 형식 목록"],
  ["ASTC", "에이에스티씨", "모바일 텍스처 압축 형식"],
  ["NetworkVariable", "네트워크 배리어블", "Netcode — 자동 동기화 변수"],

  /* ── 스프링 대응(비교 표) ── */
  ["@Transactional", "트랜잭셔널", "스프링 트랜잭션 경계"],
  ["@SpringBootTest", "스프링부트 테스트", "컨텍스트 전체를 띄우는 통합 테스트"],
  ["@Scheduled", "스케줄드", "스프링 주기 작업"],
  ["@ConfigurationProperties", "컨피규레이션 프로퍼티즈", "설정 묶음 바인딩 — IOptions 자리"],
  ["@Configuration", "컨피규레이션", "빈 설정 클래스"],
  ["@PostConstruct", "포스트 컨스트럭트", "빈 생성 직후 한 번"],
  ["REQUIRES_NEW", "리콰이어스 뉴", "전파 옵션 — 항상 새 트랜잭션"],
  ["collections.deque", "컬렉션스 덱", "파이썬 양방향 큐"],
  ["ArrayDeque", "어레이 덱", "자바 배열 기반 덱"],
];
