/* 읽는 법 사전 — db · shared/js/07-study.js 가 본문 인라인 코드의 탭별 첫 등장에 * 를 붙인다.
   [표기, 읽는 법, 실무에서 부르는 말·한 줄 뜻(선택)] — 표기는 코드에 나오는 그대로(대소문자 구분) */
window.LX_SAY = [
  /* ── 제품 · 클라이언트 ── */
  ["postgresql", "포스트그레스큐엘", "PostgreSQL — 줄여서 '포스트그레스 · 포그'"],
  ["PostgreSQL", "포스트그레스큐엘", "줄여서 '포스트그레스 · 포그'"],
  ["postgres", "포스트그레스", "PostgreSQL 의 짧은 이름 · 기본 슈퍼유저"],
  ["psql", "피에스큐엘", "PostgreSQL 명령줄 클라이언트"],
  ["mysql", "마이에스큐엘", "MySQL 명령줄 클라이언트 — '마이시퀄'이라고도"],
  ["MySQL", "마이에스큐엘 / 마이시퀄", "오픈소스 RDBMS"],
  ["sqlite3", "에스큐엘라이트 쓰리 / 시퀄라이트", "SQLite 명령줄 셸"],
  ["redis-cli", "레디스 씨엘아이", "Redis 명령줄 클라이언트"],
  ["mongosh", "몽고쉘", "MongoDB 셸"],
  ["dbeaver", "디비버", "범용 DB GUI 도구"],
  ["FREEPDB1", "프리 피디비 원", "Oracle Free 의 기본 플러거블 DB"],
  ["lsnrctl", "리스너 컨트롤", "Oracle 리스너 관리 명령"],
  ["pg_hba.conf", "피지 에이치비에이 컨프", "PostgreSQL 접속 허용 규칙 파일"],
  ["postgresql.conf", "포스트그레스큐엘 컨프", "PostgreSQL 서버 설정 파일"],
  ["my.cnf", "마이 씨엔에프", "MySQL 설정 파일"],
  ["compose.yml", "컴포즈 와이엠엘", "Docker Compose 정의 파일"],
  ["host.docker.internal", "호스트 닷 도커 닷 인터널", "컨테이너에서 본 호스트 PC 주소"],
  ["scram-sha-256", "스크램 샤 이오육", "PostgreSQL 비밀번호 인증 방식"],
  ["caching_sha2_password", "캐싱 샤투 패스워드", "MySQL 8 기본 인증 플러그인"],
  ["sslmode", "에스에스엘 모드", "접속 TLS 사용 여부"],
  ["PGPASSWORD", "피지패스워드", "psql 비밀번호 환경변수"],
  ["requirepass", "리콰이어패스", "Redis 비밀번호 설정"],

  /* ── SQL 기본 ── */
  ["SELECT *", "셀렉트 스타 / 셀렉트 올", "모든 컬럼 — 운영 코드에선 피함"],
  ["JOIN", "조인", "테이블 붙이기"],
  ["LEFT JOIN", "레프트 조인", "왼쪽은 다 남기고 붙이기 — '레프트 아우터'"],
  ["CROSS JOIN", "크로스 조인", "모든 조합(카티션 곱)"],
  ["CROSS APPLY", "크로스 어플라이", "SQL Server 의 LATERAL 조인"],
  ["ORDER BY", "오더 바이", "정렬"],
  ["GROUP BY", "그룹 바이", "묶어서 집계"],
  ["DISTINCT", "디스팅트", "중복 제거"],
  ["BETWEEN", "비트윈", "범위 조건 — 양끝 포함"],
  ["LIKE", "라이크", "패턴 검색 — % 는 아무 문자열"],
  ["EXISTS", "이그지스츠", "행이 있는지만 확인 — 세미 조인"],
  ["NOT EXISTS", "낫 이그지스츠", "없는 행 찾기 — 안티 조인"],
  ["UNION", "유니언", "결과 합치기 — 중복 제거"],
  ["UNION ALL", "유니언 올", "결과 합치기 — 중복 그대로, 더 빠름"],
  ["CASE WHEN", "케이스 웬", "조건 분기 식"],
  ["IS NULL", "이즈 널", "NULL 검사 — = NULL 은 항상 거짓"],
  ["NOT NULL", "낫 널", "NULL 금지 제약"],
  ["LIMIT", "리밋", "가져올 행 수 제한"],
  ["OFFSET", "오프셋", "앞에서 건너뛸 행 수 — 깊어지면 느림"],
  ["FETCH FIRST", "페치 퍼스트", "표준 SQL 행 수 제한"],
  ["NULLS FIRST", "널스 퍼스트", "정렬에서 NULL 을 앞으로"],
  ["NULLS LAST", "널스 라스트", "정렬에서 NULL 을 뒤로"],
  ["PRIMARY KEY", "프라이머리 키", "기본 키 — 'PK · 피케이'"],
  ["FOREIGN KEY", "포린 키", "외래 키 — 'FK · 에프케이'"],
  ["CASCADE", "캐스케이드", "부모를 지우면 자식도 같이"],
  ["TRUNCATE", "트렁케이트", "테이블 비우기 — 로그 적게, 되돌리기 어려움"],
  ["MERGE", "머지", "있으면 UPDATE 없으면 INSERT — 표준 upsert"],
  ["ON CONFLICT", "온 컨플릭트", "PostgreSQL·SQLite upsert"],
  ["ON DUPLICATE KEY UPDATE", "온 듀플리케이트 키 업데이트", "MySQL upsert"],
  ["RETURNING", "리터닝", "바꾼 행을 바로 돌려받기"],
  ["LATERAL", "래터럴", "앞 테이블의 행마다 서브쿼리 실행"],
  ["WITH RECURSIVE", "위드 리커시브", "재귀 CTE — 트리·계층 탐색"],
  ["CONNECT BY", "커넥트 바이", "Oracle 계층 쿼리"],
  ["SYS_CONNECT_BY_PATH", "시스 커넥트 바이 패스", "Oracle — 루트부터의 경로 문자열"],
  ["GRANT", "그랜트", "권한 주기"],
  ["REVOKE", "리보크", "권한 회수"],
  ["BEGIN", "비긴", "트랜잭션 시작"],
  ["COMMIT", "커밋", "확정"],
  ["ROLLBACK", "롤백", "되돌리기"],
  ["MATERIALIZED", "머티리얼라이즈드", "결과를 저장해 두는 뷰·CTE"],
  ["GENERATED", "제너레이티드", "자동 생성 컬럼(IDENTITY·계산 컬럼)"],
  ["COVERING INDEX", "커버링 인덱스", "쿼리에 필요한 컬럼이 다 들어 있는 인덱스"],

  /* ── 함수 · 윈도 ── */
  ["COALESCE", "코얼레스", "처음으로 NULL 아닌 값"],
  ["NULLIF", "널이프", "두 값이 같으면 NULL"],
  ["NVL", "엔브이엘", "Oracle — NULL 이면 대체값"],
  ["NVL2", "엔브이엘 투", "Oracle — NULL 여부에 따라 두 값 중 하나"],
  ["IFNULL", "이프널", "MySQL·SQLite — NULL 이면 대체값"],
  ["DECODE", "디코드", "Oracle 의 간이 CASE"],
  ["CAST", "캐스트", "형 변환"],
  ["LPAD", "엘패드", "왼쪽을 채워 길이 맞추기"],
  ["SUBSTR", "서브스트링 / 섭스터", "문자열 자르기(Oracle·SQLite)"],
  ["SUBSTRING", "서브스트링", "문자열 자르기(표준)"],
  ["INSTR", "인스터 / 인스트링", "문자열 위치 찾기"],
  ["CONCAT", "콘캣", "문자열 잇기"],
  ["REGEXP_REPLACE", "레젝스 리플레이스", "정규식 치환"],
  ["LISTAGG", "리스트애그", "Oracle — 여러 행을 한 문자열로"],
  ["STRING_AGG", "스트링 애그", "PostgreSQL·SQL Server — 여러 행을 한 문자열로"],
  ["GROUP_CONCAT", "그룹 콘캣", "MySQL·SQLite — 여러 행을 한 문자열로"],
  ["SYSDATE", "시스데이트", "Oracle 현재 시각"],
  ["TO_DATE", "투데이트", "문자열 → 날짜(Oracle·PG)"],
  ["TO_CHAR", "투캐릭터 / 투차", "날짜·숫자 → 문자열"],
  ["TRUNC", "트렁크", "날짜·숫자 자르기"],
  ["DATE_TRUNC", "데이트 트렁크", "PostgreSQL — 날짜를 단위로 자르기"],
  ["DATE_FORMAT", "데이트 포맷", "MySQL 날짜 → 문자열"],
  ["STR_TO_DATE", "스트 투 데이트", "MySQL 문자열 → 날짜"],
  ["strftime", "에스티알 에프 타임 / 스트링 포맷 타임", "SQLite 날짜 형식 함수"],
  ["ADD_MONTHS", "애드 먼스", "Oracle — 개월 더하기"],
  ["DUAL", "듀얼", "Oracle 의 한 행짜리 가짜 테이블"],
  ["ROWNUM", "로우넘", "Oracle 결과 행 번호(가상 컬럼)"],
  ["OVER", "오버", "윈도 함수 범위 지정"],
  ["PARTITION BY", "파티션 바이", "윈도를 그룹별로 나누기"],
  ["ROW_NUMBER", "로우 넘버", "1부터 매기는 순번"],
  ["RANK", "랭크", "동점은 같은 순위, 다음 순위 건너뜀"],
  ["DENSE_RANK", "덴스 랭크", "동점은 같은 순위, 건너뛰지 않음"],
  ["NTILE", "엔타일", "N 개 구간으로 나누기"],
  ["LAG", "래그", "앞 행 값"],
  ["LEAD", "리드", "뒤 행 값"],
  ["FIRST_VALUE", "퍼스트 밸류", "윈도의 첫 값"],
  ["PERCENTILE_CONT", "퍼센타일 컨트", "연속 백분위수 — 중앙값"],
  ["ROWS BETWEEN", "로우스 비트윈", "윈도 프레임 범위"],
  ["UNBOUNDED PRECEDING", "언바운디드 프리시딩", "처음 행부터"],
  ["CURRENT ROW", "커런트 로우", "현재 행까지"],
  ["ROLLUP", "롤업", "소계·총계 행 추가"],
  ["GROUPING SETS", "그루핑 세츠", "여러 GROUP BY 를 한 번에"],
  ["QUALIFY", "퀄리파이", "윈도 함수 결과로 거르기(DuckDB 등)"],
  ["TABLESAMPLE", "테이블샘플", "표본 행만 읽기"],

  /* ── 타입 · 문자셋 ── */
  ["VARCHAR", "바차 / 바캐릭터", "가변 길이 문자열"],
  ["VARCHAR2", "바차 투", "Oracle 가변 문자열"],
  ["NUMERIC", "뉴메릭", "정확한 10진수 — 돈"],
  ["BIGINT", "빅인트", "8바이트 정수"],
  ["TIMESTAMP", "타임스탬프", "날짜+시각"],
  ["TIMESTAMPTZ", "타임스탬프 티지", "PostgreSQL 시간대 포함 시각"],
  ["DATETIME", "데이트타임", "MySQL 날짜+시각(시간대 없음)"],
  ["INTERVAL", "인터벌", "기간 값"],
  ["AUTO_INCREMENT", "오토 인크리먼트", "MySQL 자동 증가 키"],
  ["AUTOINCREMENT", "오토인크리먼트", "SQLite 자동 증가(재사용 안 함)"],
  ["JSONB", "제이슨비", "PostgreSQL 이진 JSON — 인덱스 가능"],
  ["utf8mb4", "유티에프팔 엠비포", "MySQL 진짜 UTF-8(이모지 포함)"],
  ["utf8mb4_0900_ai_ci", "유티에프팔엠비포 공구공공 에이아이 씨아이", "악센트·대소문자 무시 정렬 규칙"],
  ["sql_mode", "에스큐엘 모드", "MySQL 엄격 모드 등 동작 설정"],
  ["ONLY_FULL_GROUP_BY", "온리 풀 그룹 바이", "GROUP BY 에 없는 컬럼 선택 금지"],
  ["PIPES_AS_CONCAT", "파이프스 애즈 콘캣", "MySQL 에서 || 를 문자열 잇기로"],
  ["uuidv7", "유유아이디 브이세븐", "시간순 정렬되는 UUID"],

  /* ── 연산자 ── */
  ["@>", "포함 연산자", "JSONB·배열 — 왼쪽이 오른쪽을 포함"],
  ["->>", "화살표 두 개 / 텍스트 추출", "JSON 필드를 텍스트로 꺼내기"],
  ["<->", "거리 연산자", "pgvector L2 거리 · pg_trgm 유사도 거리"],
  ["<=>", "코사인 거리 연산자", "pgvector 코사인 거리"],
  ["<#>", "내적 연산자", "pgvector 음의 내적"],

  /* ── 실행 계획 · 튜닝 ── */
  ["EXPLAIN", "익스플레인", "실행 계획 보기"],
  ["ANALYZE", "애널라이즈", "통계 갱신 · EXPLAIN 과 쓰면 실제 실행"],
  ["VACUUM", "배큠", "죽은 튜플 정리 — PostgreSQL·SQLite"],
  ["VACUUM FULL", "배큠 풀", "테이블 재작성 — 배타 잠금"],
  ["REINDEX", "리인덱스", "인덱스 다시 만들기"],
  ["CONCURRENTLY", "컨커런틀리", "쓰기를 막지 않고 인덱스 생성·재작성"],
  ["CREATE INDEX CONCURRENTLY", "크리에이트 인덱스 컨커런틀리", "운영 중 무중단 인덱스 생성"],
  ["Seq Scan", "시퀀셜 스캔 / 시크 스캔", "테이블 전체 읽기"],
  ["Index Only Scan", "인덱스 온리 스캔", "테이블 안 가고 인덱스만으로 끝"],
  ["Bitmap Heap Scan", "비트맵 힙 스캔", "인덱스로 모은 위치를 묶어 테이블 읽기"],
  ["Nested Loop", "네스티드 루프", "바깥 행마다 안쪽 찾기 — 'NL 조인'"],
  ["Hash Join", "해시 조인", "한쪽을 해시로 만들어 붙이기"],
  ["Merge Join", "머지 조인", "정렬된 두 입력을 맞춰 붙이기"],
  ["Using filesort", "유징 파일소트", "MySQL — 인덱스로 정렬 못 함"],
  ["Using temporary", "유징 템포러리", "MySQL — 임시 테이블 사용"],
  ["Using index", "유징 인덱스", "MySQL — 커버링 인덱스로 끝"],
  ["eq_ref", "이큐 레프", "MySQL — PK·유니크로 한 행씩 조인"],
  ["pt-query-digest", "피티 쿼리 다이제스트", "슬로 쿼리 로그 요약 도구"],
  ["pg_stat_statements", "피지 스탯 스테이트먼츠", "쿼리별 누적 통계 확장"],
  ["GATHER_PLAN_STATISTICS", "개더 플랜 스태티스틱스", "Oracle — 실제 행 수까지 수집하는 힌트"],
  ["USE_NL", "유즈 엔엘", "Oracle — NL 조인 힌트"],
  ["work_mem", "워크 멤", "PostgreSQL 정렬·해시 메모리"],
  ["shared_buffers", "셰어드 버퍼스", "PostgreSQL 공유 캐시 크기"],
  ["effective_cache_size", "이펙티브 캐시 사이즈", "OS 캐시까지 포함한 추정치 — 플래너용"],
  ["random_page_cost", "랜덤 페이지 코스트", "랜덤 읽기 비용 — SSD 면 낮춤"],
  ["max_wal_size", "맥스 왈 사이즈", "체크포인트 전 WAL 상한"],
  ["max_connections", "맥스 커넥션스", "최대 동시 접속 수"],
  ["log_min_duration_statement", "로그 민 듀레이션 스테이트먼트", "이 시간 넘는 쿼리 기록"],
  ["innodb_buffer_pool_size", "이노디비 버퍼 풀 사이즈", "InnoDB 캐시 크기 — 보통 RAM 의 50~70%"],
  ["innodb_flush_log_at_trx_commit", "이노디비 플러시 로그 앳 트랜잭션 커밋", "커밋마다 디스크 동기화 여부"],
  ["innodb_lock_wait_timeout", "이노디비 락 웨잇 타임아웃", "행 잠금 대기 한도"],
  ["slow_query_log", "슬로 쿼리 로그", "느린 쿼리 기록"],
  ["long_query_time", "롱 쿼리 타임", "느린 쿼리 기준 초"],
  ["idle_in_transaction_session_timeout", "아이들 인 트랜잭션 세션 타임아웃", "트랜잭션 열고 놀면 끊기"],
  ["fillfactor", "필팩터", "페이지를 얼마나 채울지 — HOT 업데이트 여유"],
  ["PCTFREE", "피씨티프리", "Oracle — 블록 여유 공간 비율"],
  ["pg_repack", "피지 리팩", "잠금 최소로 테이블 재작성"],
  ["n_dead_tup", "엔 데드 텁", "죽은 튜플 수"],
  ["pg_advisory_lock", "피지 어드바이저리 락", "앱이 정하는 이름 잠금"],
  ["pg_dump", "피지 덤프", "PostgreSQL 백업"],
  ["mysqldump", "마이에스큐엘덤프", "MySQL 백업"],
  ["single-transaction", "싱글 트랜잭션", "mysqldump 일관성 스냅숏 옵션"],
  ["pg_upgrade", "피지 업그레이드", "PostgreSQL 메이저 버전 올리기"],
  ["archive_command", "아카이브 커맨드", "WAL 보관 명령"],
  ["pool_mode", "풀 모드", "PgBouncer 풀링 방식(transaction 등)"],
  ["LISTEN", "리슨", "PostgreSQL 알림 구독"],
  ["NOTIFY", "노티파이", "PostgreSQL 알림 보내기"],

  /* ── SQLite ── */
  ["PRAGMA", "프라그마", "SQLite 설정 명령"],
  ["journal_mode", "저널 모드", "SQLite 쓰기 로그 방식 — WAL 권장"],
  ["WAL", "왈 / 더블유에이엘", "Write-Ahead Log — 먼저 로그에 쓰기"],
  ["busy_timeout", "비지 타임아웃", "잠겨 있으면 이만큼 기다림"],

  /* ── Redis · MongoDB ── */
  ["INCR", "인크르 / 인크리먼트", "원자적 1 증가"],
  ["HGET", "에이치겟", "해시 필드 읽기"],
  ["LPUSH", "엘푸시", "리스트 왼쪽에 넣기"],
  ["ZADD", "지애드 / 제드애드", "정렬 집합에 점수와 넣기"],
  ["ZRANGE", "지레인지", "정렬 집합 범위 조회 — 랭킹"],
  ["UNLINK", "언링크", "비동기 삭제 — 큰 키는 DEL 대신"],
  ["KEYS", "키스", "패턴 키 전체 조회 — 운영 금지, SCAN 사용"],
  ["MULTI", "멀티", "트랜잭션 묶음 시작"],
  ["noeviction", "노이빅션", "메모리 차면 쓰기 거부"],
  ["allkeys-lru", "올키스 엘알유", "메모리 차면 오래 안 쓴 키부터 제거"],
  ["updateOne", "업데이트원", "문서 하나 수정"],
  ["$lookup", "룩업", "MongoDB 집계의 조인"],
  ["$match", "매치", "MongoDB 집계의 필터"],
  ["$group", "그룹", "MongoDB 집계의 GROUP BY"],
  ["COLLSCAN", "콜스캔", "MongoDB 컬렉션 전체 스캔"],
  ["IXSCAN", "아이엑스스캔 / 인덱스 스캔", "MongoDB 인덱스 스캔"],
  ["readPreference", "리드 프리퍼런스", "어느 노드에서 읽을지"],
  ["majority", "머조리티", "과반 노드 확인 — 쓰기·읽기 일관성"],

  /* ── 분석(OLAP) · 벡터 ── */
  ["ReplacingMergeTree", "리플레이싱 머지트리", "ClickHouse — 병합 때 중복 행 정리"],
  ["toYYYYMM", "투 와이와이와이와이 엠엠", "ClickHouse — 연월 숫자로"],
  ["FINAL", "파이널", "ClickHouse — 병합 결과로 읽기(느림)"],
  ["TOO_MANY_PARTS", "투 매니 파츠", "ClickHouse — 작은 INSERT 남발 오류"],
  ["LowCardinality", "로우 카디널리티", "ClickHouse — 값 종류가 적은 컬럼 사전 인코딩"],
  ["arrayJoin", "어레이 조인", "ClickHouse — 배열을 행으로 펼치기"],
  ["read_parquet", "리드 파케이", "DuckDB — Parquet 파일 읽기"],
  ["ivfflat", "아이브이에프플랫", "pgvector 군집 기반 근사 인덱스"],
  ["hnsw.ef_search", "에이치엔에스더블유 이에프 서치", "검색 때 후보 폭 — 크면 정확·느림"],
  ["sparsevec", "스파스벡", "pgvector 희소 벡터 형식"],
  ["ltree", "엘트리", "PostgreSQL 계층 경로 타입"],
  ["unnest", "언네스트", "배열을 행으로 펼치기"],

  /* ── 마이그레이션 · 앱 연동 ── */
  ["flyway", "플라이웨이", "버전 번호 SQL 마이그레이션 도구"],
  ["liquibase", "리퀴베이스", "변경 로그 기반 마이그레이션 도구"],
  ["alembic", "알렘빅", "SQLAlchemy 마이그레이션 도구"],
  ["prisma", "프리즈마", "Node ORM·마이그레이션"],
  ["drizzle-kit", "드리즐 킷", "Drizzle ORM 마이그레이션 CLI"],
  ["sqlx", "에스큐엘엑스", "Rust·Go 의 SQL 라이브러리"],
  ["sqlc", "에스큐엘씨", "SQL 에서 타입 안전 코드 생성"],
  ["sqlfluff", "에스큐엘플러프", "SQL 린터"],
  ["testcontainers", "테스트컨테이너스", "테스트 때 진짜 DB 를 컨테이너로 띄움"],
  ["DATABASE_URL", "데이터베이스 유알엘", "접속 문자열 환경변수"],
  ["selectinload", "셀렉트인 로드", "SQLAlchemy — IN 절로 연관 미리 읽기"],
  ["ddl-auto", "디디엘 오토", "JPA 스키마 자동 생성 옵션"],
];
