/* 읽는 법 사전 — kotlin · shared/js/07-study.js 가 본문 인라인 코드의 탭별 첫 등장에 * 를 붙인다.
   [표기, 읽는 법, 실무에서 부르는 말·한 줄 뜻(선택)] — 표기는 코드에 나오는 그대로(대소문자 구분) */
window.LX_SAY = [
  /* 언어 키워드·연산자 */
  ["suspend", "서스펜드", "'서스펜드 함수' — 멈췄다 이어서 도는 함수"],
  ["suspend fun", "서스펜드 펀", "서스펜드 함수 선언. fun 은 '펀'으로 읽음"],
  ["!!", "느낌표 두 개 / 뱅뱅", "널 아님 단언 — 널이면 NPE. '더블 뱅'이라고도 부름"],
  ["?.", "물음표 점 / 세이프 콜", "널이면 호출 안 하고 null — '세이프 콜 연산자'"],
  ["?:", "엘비스", "엘비스 연산자 — 왼쪽이 null 이면 오른쪽 값"],
  ["?.let", "세이프 콜 렛", "널 아닐 때만 블록 실행 — '물음표 점 렛'"],
  ["T?", "티 물음표 / 널러블 티", "null 이 들어올 수 있는 T"],
  ["Any?", "애니 물음표 / 널러블 애니", "코틀린 최상위 타입(null 포함)"],
  ["String!", "스트링 느낌표 / 플랫폼 타입", "자바에서 온 널 여부 모르는 타입"],
  ["val", "발", "읽기 전용 변수. '밸'이라고도 함"],
  ["var", "바 / 바르", "다시 대입 가능한 변수"],
  ["const val", "콘스트 발", "컴파일 타임 상수"],
  ["lateinit", "레이트이닛", "'레이트 이니셜라이즈' — 나중에 초기화할 var"],
  ["lateinit var", "레이트이닛 바", "나중에 채우는 non-null 프로퍼티"],
  ["by lazy", "바이 레이지", "처음 쓸 때 한 번만 계산 — '레이지 위임'"],
  ["object", "오브젝트", "싱글턴 선언 — '오브젝트 선언'"],
  ["companion object", "컴패니언 오브젝트", "클래스에 딸린 싱글턴 — 자바 static 대용"],
  ["data class", "데이터 클래스", "equals·hashCode·copy 자동 생성 클래스"],
  ["value class", "밸류 클래스", "값 하나를 감싸는 래퍼 — 런타임엔 풀림"],
  ["@JvmInline", "제이브이엠 인라인", "value class 에 붙이는 어노테이션"],
  ["sealed", "실드", "'실드 클래스' — 하위 타입이 닫힌 계층"],
  ["inline", "인라인", "호출 자리에 함수 본문을 펼쳐 넣음"],
  ["crossinline", "크로스인라인", "인라인 람다에서 non-local return 금지"],
  ["reified", "레이파이드 / 리이파이드", "실체화 타입 — 런타임에 T 를 볼 수 있음"],
  ["open", "오픈", "상속·오버라이드 허용 — 코틀린은 기본 final"],
  ["internal", "인터널", "같은 모듈 안에서만 보이는 가시성"],
  ["init", "이닛", "'이닛 블록' — 주 생성자 직후 실행"],
  ["out", "아웃", "공변(생산 전용) 타입 파라미터"],
  ["when", "웬", "'웬 식' — switch 대신 쓰는 분기 식"],
  ["typealias", "타입에일리어스", "타입 별칭"],
  ["fun interface", "펀 인터페이스", "추상 메서드 하나짜리 인터페이스 — SAM"],
  ["field", "필드", "'백킹 필드' — 접근자 안에서 실제 저장소"],
  ["return@forEach", "리턴 앳 포이치", "라벨 리턴 — 현재 람다만 빠져나감"],
  ["componentN", "컴포넌트 엔", "구조 분해 선언이 부르는 함수"],
  ["ordinal", "오디널", "enum 선언 순서 번호"],
  ["@field:", "앳 필드", "어노테이션 사용처 지정 — 필드에 붙임"],
  ["@get:", "앳 겟", "어노테이션 사용처 지정 — getter 에 붙임"],
  ["@Throws", "스로우즈", "자바 쪽에 checked 예외 알림"],
  ["@JvmOverloads", "제이브이엠 오버로즈", "기본 인자별 오버로드를 자바용으로 생성"],
  ["@JvmName", "제이브이엠 네임", "자바에서 보일 이름 지정"],
  ["@Volatile", "볼라틸", "메모리 가시성 보장 필드"],

  /* 표준 함수 */
  ["let", "렛", "스코프 함수 — it 으로 받고 결과 반환"],
  ["run", "런", "스코프 함수 — this 로 받고 결과 반환"],
  ["apply", "어플라이", "스코프 함수 — 설정 후 자기 자신 반환"],
  ["also", "올소", "스코프 함수 — 부수 작업 후 자기 자신 반환"],
  ["with", "위드", "스코프 함수 — 인자를 this 로"],
  ["takeIf", "테이크이프", "조건 맞으면 자신, 아니면 null"],
  ["runCatching", "런캐칭", "예외를 Result 로 감싸 실행"],
  ["getOrThrow", "겟오어스로우", "Result 에서 값 꺼내거나 예외 다시 던짐"],
  ["use", "유즈", "다 쓰면 자동 close — 자바 try-with-resources"],
  ["useLines", "유즈라인즈", "파일 줄 시퀀스를 쓰고 자동으로 닫음"],
  ["asSequence", "애즈시퀀스", "지연 평가 시퀀스로 전환"],
  ["Sequence", "시퀀스", "지연 평가 컬렉션"],
  ["buildString", "빌드스트링", "StringBuilder 블록으로 문자열 만들기"],
  ["joinToString", "조인투스트링", "구분자로 이어 붙인 문자열"],
  ["requireNotNull", "리콰이어 낫 널", "인자 검증 — 실패 시 IllegalArgumentException"],
  ["checkNotNull", "체크 낫 널", "상태 검증 — 실패 시 IllegalStateException"],
  ["isNullOrEmpty", "이즈 널 오어 엠티", "null 이거나 빈 값"],
  ["isNullOrBlank", "이즈 널 오어 블랭크", "null 이거나 공백뿐"],
  ["Delegates.observable", "델리게이츠 옵저버블", "값 바뀔 때마다 콜백"],
  ["Delegates.notNull", "델리게이츠 낫널", "나중에 채우는 원시 타입용 위임"],
  ["UninitializedPropertyAccessException", "언이니셜라이즈드 프로퍼티 액세스 익셉션", "lateinit 을 채우기 전에 읽음"],

  /* 코루틴 */
  ["launch", "런치", "결과 없는 코루틴 시작 — Job 반환"],
  ["async", "어싱크 / 에이싱크", "결과 있는 코루틴 시작 — Deferred 반환"],
  ["await", "어웨이트", "Deferred 결과 기다려 받기"],
  ["Deferred", "디퍼드", "나중에 값이 오는 결과 — async 반환형"],
  ["Job", "잡", "코루틴 하나의 손잡이 — 취소·대기"],
  ["SupervisorJob", "슈퍼바이저잡", "자식 실패가 형제로 안 번지는 Job"],
  ["runBlocking", "런블로킹", "스레드를 막고 코루틴 실행 — main·테스트용"],
  ["withContext", "위드컨텍스트", "디스패처 바꿔 블록 실행 후 결과 반환"],
  ["coroutineScope", "코루틴스코프", "자식 다 끝날 때까지 기다리는 스코프 함수 — 소문자 c"],
  ["supervisorScope", "슈퍼바이저스코프", "자식 하나 실패해도 나머지 유지"],
  ["GlobalScope", "글로벌스코프", "앱 전체 수명 스코프 — 실무에선 금지"],
  ["viewModelScope", "뷰모델스코프", "ViewModel 정리 시 취소되는 스코프"],
  ["lifecycleScope", "라이프사이클스코프", "화면 수명에 묶인 스코프"],
  ["Dispatchers.IO", "디스패처스 아이오", "IO 디스패처 — 블로킹 I/O 용 스레드풀"],
  ["Dispatchers.Default", "디스패처스 디폴트", "CPU 연산용 스레드풀"],
  ["Dispatchers.Main", "디스패처스 메인", "UI 스레드"],
  ["Dispatchers.Unconfined", "디스패처스 언컨파인드", "스레드 고정 안 함 — 테스트·특수용"],
  ["limitedParallelism", "리미티드 패러렐리즘", "디스패처 동시 실행 수 제한"],
  ["CancellationException", "캔슬레이션 익셉션", "취소 신호 — 삼키지 말고 다시 던짐"],
  ["TimeoutCancellationException", "타임아웃 캔슬레이션 익셉션", "withTimeout 초과"],
  ["ensureActive", "인슈어액티브", "취소됐으면 즉시 예외 — 루프 안 취소 확인"],
  ["isActive", "이즈액티브", "아직 취소 안 됐는지"],
  ["yield", "일드", "다른 코루틴에게 양보"],
  ["withTimeout", "위드타임아웃", "시간 넘으면 취소"],
  ["withTimeoutOrNull", "위드타임아웃 오어 널", "시간 넘으면 null"],
  ["NonCancellable", "논캔슬러블", "취소 중에도 끝까지 실행할 정리 작업용"],
  ["Continuation", "컨티뉴에이션", "중단 지점 이후를 담은 객체 — 서스펜드의 정체"],
  ["Mutex", "뮤텍스", "코루틴용 잠금 — withLock"],
  ["Semaphore", "세마포어", "동시 진입 수 제한"],
  ["Channel", "채널", "코루틴 사이 값 전달 큐"],
  ["trySend", "트라이센드", "막히지 않고 보내 보기"],
  ["produce", "프로듀스", "채널을 만들어 값 생산하는 코루틴"],
  ["RENDEZVOUS", "랑데부", "버퍼 0 채널 — 주고받는 쪽이 만나야 전달"],
  ["CONFLATED", "컨플레이티드", "최신 값 하나만 유지"],
  ["MDCContext", "엠디씨 컨텍스트", "로그 MDC 를 코루틴에 이어 줌"],
  ["ThreadLocal", "스레드로컬", "스레드별 저장소 — 코루틴에선 끊김 주의"],
  ["DebugProbes.dumpCoroutines", "디버그 프로브스 덤프 코루틴즈", "살아 있는 코루틴 목록 출력"],
  ["-Dkotlinx.coroutines.debug", "디 코틀린엑스 코루틴즈 디버그", "로그 스레드명에 @coroutine#번호 표시"],
  ["kotlinx-coroutines-debug", "코틀린엑스 코루틴즈 디버그", "kotlinx 는 '코틀린 엑스'"],
  ["BlockHound.install", "블록하운드", "논블로킹 스레드의 블로킹 호출 탐지"],
  ["ThreadContextElement", "스레드 컨텍스트 엘리먼트", "코루틴 전환 시 ThreadLocal 복원"],

  /* Flow */
  ["Flow", "플로우", "차가운 비동기 스트림"],
  ["StateFlow", "스테이트플로우", "현재 값 하나를 가진 뜨거운 플로우"],
  ["SharedFlow", "셰어드플로우", "여러 구독자에게 뿌리는 뜨거운 플로우"],
  ["MutableSharedFlow", "뮤터블 셰어드플로우", "값을 emit 할 수 있는 SharedFlow"],
  ["collect", "콜렉트", "플로우 구독해 값 받기"],
  ["collectLatest", "콜렉트 레이티스트", "새 값 오면 이전 처리 취소"],
  ["conflate", "컨플레이트", "밀린 값은 버리고 최신만"],
  ["flowOn", "플로우온", "업스트림 실행 디스패처 지정"],
  ["flatMapConcat", "플랫맵 콘캣", "순서대로 이어 붙이기"],
  ["flatMapMerge", "플랫맵 머지", "동시에 합치기"],
  ["flatMapLatest", "플랫맵 레이티스트", "새 값 오면 이전 내부 플로우 취소"],
  ["snapshotFlow", "스냅샷플로우", "Compose 상태를 Flow 로"],
  ["Turbine", "터빈", "Flow 테스트 라이브러리"],

  /* 테스트 */
  ["runTest", "런테스트", "가상 시간으로 코루틴 테스트"],
  ["backgroundScope", "백그라운드스코프", "테스트 끝나면 자동 취소되는 스코프"],
  ["advanceTimeBy", "어드밴스타임바이", "가상 시간 앞당기기"],
  ["advanceUntilIdle", "어드밴스 언틸 아이들", "대기 작업 다 돌리기"],
  ["runCurrent", "런커런트", "지금 시각 작업만 실행"],
  ["StandardTestDispatcher", "스탠다드 테스트 디스패처", "직접 시간 진행시키는 테스트 디스패처"],
  ["UnconfinedTestDispatcher", "언컨파인드 테스트 디스패처", "즉시 실행하는 테스트 디스패처"],
  ["Dispatchers.setMain", "디스패처스 셋메인", "테스트에서 Main 디스패처 교체"],
  ["coEvery", "코에브리", "MockK — 서스펜드 함수 스텁"],
  ["coVerify", "코베리파이", "MockK — 서스펜드 함수 호출 검증"],
  ["coJustRun", "코저스트런", "MockK — Unit 서스펜드 함수 그냥 통과"],
  ["@MockkBean", "앳 목케이 빈", "SpringMockK — 빈을 MockK 목으로 교체"],
  ["@MockK", "앳 목케이", "MockK 목 필드"],
  ["mockkObject", "목케이 오브젝트", "object 싱글턴을 목으로"],
  ["mockkStatic", "목케이 스태틱", "최상위·정적 함수를 목으로"],
  ["relaxUnitFun", "릴랙스 유닛 펀", "Unit 함수는 스텁 없이 통과"],
  ["confirmVerified", "컨펌 베리파이드", "검증 안 한 호출 남았는지 확인"],
  ["@ServiceConnection", "서비스 커넥션", "Testcontainers 접속 정보 자동 주입"],
  ["@DataJpaTest", "데이터 제이피에이 테스트", "JPA 계층만 띄우는 슬라이스 테스트"],

  /* 빌드·도구 */
  ["build.gradle.kts", "빌드 그레이들 케이티에스", "코틀린 DSL 빌드 스크립트"],
  ["./gradlew", "그레이들 더블유 / 그레이들 래퍼", "프로젝트에 고정된 Gradle 실행"],
  ["./gradlew --stop", "그레이들 더블유 스톱", "Gradle 데몬 종료"],
  ["./gradlew bootRun", "그레이들 더블유 부트런", "스프링 부트 실행"],
  ["libs.versions.toml", "립스 버전스 토믈", "버전 카탈로그 파일"],
  ["jvmToolchain", "제이브이엠 툴체인", "빌드에 쓸 JDK 버전 고정"],
  ["kotlinc", "코틀린씨", "코틀린 커맨드라인 컴파일러"],
  ["-Xmx", "엑스엠엑스", "최대 힙 크기 옵션"],
  ["implementation", "임플리먼테이션", "Gradle 의존성 구성 — 외부로 노출 안 됨"],
  ["api", "에이피아이", "Gradle 의존성 구성 — 소비자에게도 노출"],
  ["commonMain", "커먼메인", "KMP 공통 코드 소스셋"],
  ["expect", "익스펙트", "KMP — 공통에서 선언만"],
  ["actual", "액추얼", "KMP — 플랫폼별 실제 구현"],
  ["expect/actual", "익스펙트 액추얼", "KMP 플랫폼 분기 방식"],
  ["all-open", "올오픈", "컴파일러 플러그인 — 지정 클래스 자동 open"],
  ["no-arg", "노아그", "컴파일러 플러그인 — 기본 생성자 생성"],
  ["adb devices", "에이디비 디바이시즈", "연결된 기기 목록"],
  ["adb reverse", "에이디비 리버스", "기기 포트를 PC 로 연결"],
  ["proguard-rules.pro", "프로가드 룰즈", "난독화·축소 규칙 파일"],

  /* 스프링·직렬화 */
  ["@Transactional", "트랜잭셔널"],
  ["@RestControllerAdvice", "레스트 컨트롤러 어드바이스", "전역 예외 처리 클래스"],
  ["@ExceptionHandler", "익셉션 핸들러", "예외별 응답 메서드"],
  ["@Cacheable", "캐셔블 / 캐시어블", "결과 캐시"],
  ["@Nullable", "널러블", "널 가능 표시 — 코틀린이 T? 로 읽음"],
  ["@Serializable", "시리얼라이저블", "kotlinx.serialization 대상 표시"],
  ["@ManyToOne", "매니투원", "N:1 연관관계"],
  ["LazyInitializationException", "레이지 이니셜라이제이션 익셉션", "세션 밖에서 지연 로딩 접근"],
  ["open-in-view: false", "오픈 인 뷰 폴스", "OSIV 끄기 — '오에스아이브이'"],
  ["CompletableFuture", "컴플리터블 퓨처", "자바 비동기 결과 객체"],
  ["coRouter", "코라우터", "WebFlux 코루틴 함수형 라우터"],
  ["TransactionalOperator", "트랜잭셔널 오퍼레이터", "리액티브 프로그래밍 방식 트랜잭션"],
  ["Mono", "모노", "0~1개 리액티브 결과"],
  ["Flux", "플럭스", "0~N개 리액티브 스트림"],
  ["awaitSingle", "어웨이트싱글", "Mono 결과를 서스펜드로 받기"],
  ["subscribeOn", "서브스크라이브온", "구독 실행 스케줄러 지정"],
  ["newSuspendedTransaction", "뉴 서스펜디드 트랜잭션", "Exposed 코루틴 트랜잭션"],
  ["CORS", "코스 / 씨오알에스", "교차 출처 요청 허용 정책"],
  ["traceId", "트레이스 아이디", "요청 추적 ID"],
  ["SIGTERM", "시그텀", "종료 요청 신호 — 그레이스풀 셧다운 시작"],

  /* Ktor */
  ["install", "인스톨", "Ktor 플러그인 설치"],
  ["StatusPages", "스테이터스 페이지스", "Ktor 예외→응답 플러그인"],
  ["ContentNegotiation", "콘텐트 네고시에이션", "Ktor 직렬화 플러그인"],
  ["CallLogging", "콜 로깅", "Ktor 요청 로그 플러그인"],
  ["CallId", "콜 아이디", "Ktor 요청 ID 플러그인"],
  ["testApplication", "테스트 애플리케이션", "Ktor 서버 테스트 블록"],
  ["call.respond", "콜 리스판드", "Ktor 응답 보내기"],
  ["call.receive", "콜 리시브", "Ktor 요청 본문 받기"],
  ["RoutingContext", "라우팅 컨텍스트", "Ktor 라우트 핸들러 수신 객체"],
  ["EngineMain", "엔진메인", "설정 파일로 Ktor 서버 시작"],
  ["cio", "씨아이오", "Ktor 순수 코틀린 엔진"],

  /* Compose·안드로이드 */
  ["@Composable", "컴포저블", "UI 를 그리는 함수 표시"],
  ["@Immutable", "이뮤터블", "Compose 안정 타입 표시"],
  ["remember", "리멤버", "리컴포지션 사이에 값 보관"],
  ["rememberCoroutineScope", "리멤버 코루틴스코프", "컴포저블에 묶인 코루틴 스코프"],
  ["LaunchedEffect", "런치드 이펙트", "키가 바뀌면 재시작하는 코루틴 효과"],
  ["DisposableEffect", "디스포저블 이펙트", "정리 콜백 있는 효과"],
  ["SideEffect", "사이드 이펙트", "리컴포지션 성공마다 실행"],
  ["rememberUpdatedState", "리멤버 업데이티드 스테이트", "오래 도는 효과에 최신 값 전달"],
  ["produceState", "프로듀스 스테이트", "비동기 값을 State 로"],
  ["Modifier", "모디파이어", "Compose 크기·여백·동작 꾸밈"],
  ["SharingStarted.WhileSubscribed(5_000)", "셰어링 스타티드 와일 서브스크라이브드", "구독 끊기고 5초 뒤 업스트림 정지"],
  ["EncryptedSharedPreferences", "인크립티드 셰어드 프리퍼런스", "암호화 키값 저장소"],
  ["FLAG_IMMUTABLE", "플래그 이뮤터블", "PendingIntent 변경 불가 플래그"],
  /* 토큰 단위 매치용 추가 — 인라인 코드 안에 섞여 나오는 키워드·기호 */
  ["vararg", "바라그 / 가변 인자", "개수가 정해지지 않은 인자"],
  ["as?", "애즈 물음표 / 세이프 캐스트", "캐스트 실패하면 예외 대신 null"],
  ["===", "삼중 등호 / 트리플 이퀄", "참조 동일성 비교 — 자바의 =="],
  ["->", "화살표 / 애로우", "람다 본문·함수 타입·when 분기 구분"],
  ["it", "잇", "람다 인자가 하나일 때 붙는 기본 이름"],
  ["Nothing", "낫싱", "절대 정상 반환 안 하는 타입 — throw·TODO 의 타입"],
  ["Any", "애니", "코틀린 최상위 타입 — 자바 Object 자리"],
  ["Unit", "유닛", "반환값 없음 — 자바 void 자리"],
  ["private set", "프라이빗 셋", "밖에선 읽기만, 안에서만 대입"],
  ["lazy", "레이지", "처음 쓸 때 계산하는 위임"],
  ["require", "리콰이어", "인자 검증 — 실패 시 IllegalArgumentException"],
  ["repeat", "리피트", "n번 반복 실행"],
  ["associateBy", "어소시에이트 바이", "키를 뽑아 Map 으로"],
  ["buildList", "빌드리스트", "블록에서 add 해 읽기 전용 List 만들기"],
  ["getValue", "겟밸류", "위임 프로퍼티가 부르는 연산자 함수"],
  ["rangeUntil", "레인지 언틸", "..< 연산자의 함수 이름"],
  ["vetoable", "비토어블", "조건 안 맞으면 대입 거부하는 위임"],
  ["generateSequence", "제너레이트 시퀀스", "이전 값으로 다음 값 만드는 무한 시퀀스"],
  ["measureTime", "메저타임", "블록 실행 시간 재기"],
  ["Regex", "레젝스 / 정규식", "정규식 객체"],
  ["println", "프린트엘엔 / 프린트라인", "줄바꿈 출력"],
  ["readln", "리드엘엔 / 리드라인", "콘솔 한 줄 읽기"],
  ["Throwable", "스로어블", "모든 예외·에러의 최상위"],
  ["KClass", "케이클래스", "코틀린 클래스 참조 — Foo::class"],
  ["KProperty", "케이프로퍼티", "코틀린 프로퍼티 참조"],
  ["kotlinx", "코틀린 엑스", "코틀린 공식 확장 라이브러리 묶음"],
  ["INSTANCE", "인스턴스", "object 가 자바에서 보이는 싱글턴 필드"],
  ["jvmTarget", "제이브이엠 타깃", "생성할 바이트코드 버전"],
  ["ksp", "케이에스피", "코틀린 심볼 프로세싱 — 어노테이션 처리기"],
  ["json", "제이슨"],
  ["CoroutineName", "코루틴네임", "로그·덤프에 보일 코루틴 이름"],
  ["asCoroutineDispatcher", "애즈 코루틴 디스패처", "Executor 를 디스패처로 변환"],
  ["receiveAsFlow", "리시브 애즈 플로우", "채널을 Flow 로 — 여러 번 수집 가능"],
  ["consumeAsFlow", "컨슘 애즈 플로우", "채널을 Flow 로 — 한 번만 수집"],
  ["BUFFERED", "버퍼드", "기본 크기 버퍼 채널"],
  ["DROP_OLDEST", "드롭 올디스트", "버퍼 차면 가장 오래된 값 버림"],
  ["asFlow", "애즈플로우", "Flux·컬렉션을 Flow 로"],
  ["awaitBody", "어웨이트바디", "WebFlux 요청 본문을 서스펜드로 받기"],
  ["awaitSingleOrNull", "어웨이트 싱글 오어 널", "Mono 가 비면 null"],
  ["testScheduler", "테스트 스케줄러", "runTest 의 가상 시계"],
  ["resetMain", "리셋메인", "setMain 으로 바꾼 Main 디스패처 원복"],
  ["mockk", "목케이", "코틀린 목 라이브러리 MockK — '목크'라고도 함"],
  ["every", "에브리", "MockK — 일반 함수 스텁"],
  ["relaxed", "릴랙스드", "MockK — 스텁 없는 호출도 기본값 반환"],
  ["spyk", "스파이케이", "MockK 스파이 — 진짜 객체 일부만 목"],
  ["shouldBe", "슈드비", "Kotest 단언 — 값이 같아야 함"],
  ["assertFailsWith", "어서트 페일즈 위드", "지정 예외가 나야 통과"],
  ["inject", "인젝트", "Koin 지연 주입 — by inject()"],
  ["buildFatJar", "빌드 팻자", "Ktor — 의존성 포함 실행 jar"],
  ["@OptIn", "옵트인", "실험적 API 사용 동의"],
];
