/* 읽는 법 사전 — server · shared/js/07-study.js 가 본문 인라인 코드의 탭별 첫 등장에 * 를 붙인다.
   [표기, 읽는 법, 실무에서 부르는 말·한 줄 뜻(선택)] — 표기는 코드에 나오는 그대로(대소문자 구분) */
window.LX_SAY = [
  /* ── nginx ── */
  ["nginx", "엔진엑스", "웹 서버·리버스 프록시"],
  ["nginx -t", "엔진엑스 대시 티", "설정 문법 검사 — 리로드 전에 꼭"],
  ["nginx -s reload", "엔진엑스 리로드", "끊김 없이 설정 다시 읽기"],
  ["nginx.conf", "엔진엑스 컨프", "nginx 메인 설정 파일"],
  ["conf.d", "컨프 디", "추가 설정 파일 폴더"],
  ["sites-available", "사이츠 어베일러블", "사이트 설정 보관 폴더(데비안 계열)"],
  ["sites-enabled", "사이츠 이네이블드", "켜진 사이트 — available 로 거는 심볼릭 링크"],
  ["location", "로케이션", "URL 경로별 처리 블록"],
  ["upstream", "업스트림", "뒤쪽 백엔드 서버 묶음"],
  ["proxy_pass", "프록시 패스", "요청을 백엔드로 넘기기"],
  ["proxy_set_header", "프록시 셋 헤더", "백엔드로 보낼 헤더 지정"],
  ["proxy_read_timeout", "프록시 리드 타임아웃", "백엔드 응답 대기 한도 — 기본 60초"],
  ["proxy_buffering", "프록시 버퍼링", "응답을 모아 보낼지 — SSE·스트리밍은 off"],
  ["proxy_next_upstream", "프록시 넥스트 업스트림", "실패하면 다음 서버로 재시도"],
  ["proxy_cache", "프록시 캐시", "백엔드 응답 캐시"],
  ["proxy_buffer_size", "프록시 버퍼 사이즈", "응답 헤더용 버퍼 크기"],
  ["proxy_http_version", "프록시 에이치티티피 버전", "백엔드 연결 HTTP 버전 — keepalive 엔 1.1"],
  ["try_files", "트라이 파일스", "파일이 있으면 주고 없으면 다음 후보 — SPA 폴백"],
  ["root", "루트", "nginx — 문서 루트(경로를 이어 붙임) · 리눅스 관리자 계정"],
  ["alias", "얼라이어스 / 앨리어스", "nginx — location 부분을 경로로 바꿔 끼움 · 셸에선 명령 별칭"],
  ["listen", "리슨", "듣는 포트·주소"],
  ["server_name", "서버 네임", "가상 호스트 도메인"],
  ["default_server", "디폴트 서버", "맞는 server_name 이 없을 때 받는 블록"],
  ["add_header", "애드 헤더", "응답 헤더 추가 — 하위 블록에서 쓰면 상속 끊김"],
  ["keepalive", "킵얼라이브", "연결을 재사용 — upstream 연결 풀"],
  ["keepalive_timeout", "킵얼라이브 타임아웃", "놀고 있는 연결을 유지할 시간"],
  ["keepalive_requests", "킵얼라이브 리퀘스츠", "연결 하나당 최대 요청 수"],
  ["worker_processes", "워커 프로세시스", "워커 수 — 보통 auto(코어 수)"],
  ["worker_connections", "워커 커넥션스", "워커 하나당 최대 연결 수"],
  ["worker_rlimit_nofile", "워커 알리밋 노파일", "워커가 열 수 있는 파일 수 상한"],
  ["client_max_body_size", "클라이언트 맥스 바디 사이즈", "업로드 크기 제한 — 넘으면 413"],
  ["least_conn", "리스트 콘", "연결이 가장 적은 서버로"],
  ["ip_hash", "아이피 해시", "클라이언트 IP 로 서버 고정"],
  ["max_fails", "맥스 페일스", "이만큼 실패하면 잠시 빼기"],
  ["weight", "웨이트", "서버별 가중치"],
  ["resolver", "리졸버", "nginx 가 쓸 DNS 서버"],
  ["limit_req", "리밋 렉", "요청 속도 제한"],
  ["gzip", "지집", "응답 압축"],
  ["gzip_types", "지집 타입스", "압축할 MIME 형식"],
  ["zstd", "지스탠더드 / 젯스탠더드", "Zstandard 압축"],
  ["http2", "에이치티티피 투", "HTTP/2 켜기"],
  ["h2", "에이치투", "HTTP/2 의 ALPN 이름"],
  ["set_real_ip_from", "셋 리얼 아이피 프롬", "믿을 프록시 대역 — 진짜 클라이언트 IP 복원"],
  ["real_ip_header", "리얼 아이피 헤더", "진짜 IP 를 읽을 헤더"],
  ["log_format", "로그 포맷", "접근 로그 형식 정의"],
  ["access_log", "액세스 로그", "접근 로그 위치·형식"],
  ["error_log", "에러 로그", "오류 로그 위치·수준"],
  ["sendfile_max_chunk", "센드파일 맥스 청크", "sendfile 한 번에 보낼 최대 크기"],
  ["reuseport", "리유즈포트", "워커마다 따로 listen 소켓 — 부하 분산"],
  ["$uri", "달러 유알아이", "정규화된 요청 경로"],
  ["$host", "달러 호스트", "요청 Host"],
  ["$remote_addr", "달러 리모트 애더", "접속한 클라이언트 IP"],
  ["$binary_remote_addr", "달러 바이너리 리모트 애더", "IP 를 바이트로 — 속도 제한 키"],
  ["$request_time", "달러 리퀘스트 타임", "요청 전체 처리 시간"],
  ["$request_id", "달러 리퀘스트 아이디", "요청마다 붙는 고유 ID"],
  ["$upstream_response_time", "달러 업스트림 리스폰스 타임", "백엔드 응답에 걸린 시간"],
  ["$upstream_addr", "달러 업스트림 애더", "실제로 받은 백엔드 주소"],
  ["$upstream_connect_time", "달러 업스트림 커넥트 타임", "백엔드 연결에 걸린 시간"],
  ["$upstream_header_time", "달러 업스트림 헤더 타임", "백엔드 첫 헤더까지 시간"],
  ["$upstream_cache_status", "달러 업스트림 캐시 스테이터스", "HIT·MISS 등 캐시 결과"],
  ["$http_upgrade", "달러 에이치티티피 업그레이드", "Upgrade 요청 헤더 — 웹소켓"],
  ["$status", "달러 스테이터스", "응답 상태 코드"],

  /* ── Apache httpd ── */
  ["apachectl", "아파치 컨트롤 / 아파치씨티엘", "Apache 제어 명령"],
  ["httpd", "에이치티티피디", "Apache 데몬(레드햇 계열 이름)"],
  ["apache2", "아파치 투", "Apache(데비안 계열 이름)"],
  ["httpd.conf", "에이치티티피디 컨프", "Apache 메인 설정"],
  ["apache2.conf", "아파치 투 컨프", "데비안 계열 Apache 메인 설정"],
  [".htaccess", "에이치티액세스", "폴더별 설정 파일 — 매 요청마다 읽음"],
  ["AllowOverride", "얼라우 오버라이드", ".htaccess 허용 범위"],
  ["a2ensite", "에이투 엔사이트", "데비안 — 사이트 켜기"],
  ["a2enmod", "에이투 엔모드", "데비안 — 모듈 켜기"],
  ["ProxyPass", "프록시 패스", "Apache 리버스 프록시"],
  ["ServerName", "서버 네임", "가상 호스트 이름"],
  ["RewriteRule", "리라이트 룰", "mod_rewrite 주소 바꾸기 규칙"],
  ["RewriteCond", "리라이트 콘드", "RewriteRule 적용 조건"],
  ["SSLCertificateFile", "에스에스엘 서티피킷 파일", "Apache 인증서 경로"],
  ["MPM", "엠피엠", "Multi-Processing Module — prefork·worker·event"],
  ["MaxRequestWorkers", "맥스 리퀘스트 워커스", "Apache 동시 처리 상한"],
  ["mod_php", "모드 피에이치피", "Apache 안에서 PHP 실행 — prefork 강제"],
  ["mod_rewrite", "모드 리라이트", "URL 재작성 모듈"],
  ["php-fpm", "피에이치피 에프피엠", "PHP FastCGI 프로세스 관리자"],

  /* ── Tomcat · 앱 서버 ── */
  ["catalina.out", "카탈리나 아웃", "Tomcat 표준 출력 로그"],
  ["server.xml", "서버 엑스엠엘", "Tomcat 메인 설정"],
  ["$CATALINA_HOME", "달러 카탈리나 홈", "Tomcat 설치 경로"],
  ["maxThreads", "맥스 스레즈", "Tomcat 요청 처리 스레드 상한"],
  ["acceptCount", "억셉트 카운트", "스레드가 다 찼을 때 대기열 길이"],
  ["maxConnections", "맥스 커넥션스", "동시에 붙잡는 연결 상한"],
  ["keepAliveTimeout", "킵얼라이브 타임아웃", "놀고 있는 연결 유지 시간"],
  ["Xmx", "엑스엠엑스", "JVM 최대 힙"],
  ["XX:MaxRAMPercentage", "맥스 램 퍼센티지", "컨테이너 메모리 대비 힙 비율"],
  ["uvicorn", "유비콘", "파이썬 ASGI 서버"],
  ["gthread", "지스레드", "gunicorn 스레드 워커"],
  ["pm2", "피엠투", "Node 프로세스 관리자"],
  ["graceful", "그레이스풀", "진행 중 요청을 끝내고 종료"],

  /* ── Caddy · TLS ── */
  ["caddy", "캐디", "자동 HTTPS 웹 서버"],
  ["Caddyfile", "캐디파일", "Caddy 설정 파일"],
  ["reverse_proxy", "리버스 프록시", "Caddy 프록시 지시어"],
  ["certbot", "서트봇", "Let's Encrypt 인증서 발급 도구"],
  ["fullchain.pem", "풀체인 피이엠 / 펨", "인증서 + 중간 인증서 묶음"],
  ["privkey.pem", "프라이브키 피이엠 / 펨", "개인 키 파일"],
  ["openssl", "오픈에스에스엘", "TLS·인증서 도구"],
  ["s_client", "에스 클라이언트", "openssl TLS 접속 테스트"],
  ["TLSv1.3", "티엘에스 일 점 삼", "최신 TLS 버전"],
  ["ssl_stapling", "에스에스엘 스테이플링", "OCSP 응답을 서버가 붙여 보냄"],
  ["max-age", "맥스 에이지", "캐시·HSTS 유효 시간(초)"],
  ["no-store", "노 스토어", "아예 저장 금지"],
  ["no-cache", "노 캐시", "저장은 하되 매번 재검증"],
  ["immutable", "이뮤터블", "유효 기간 동안 재검증 안 함 — 해시 파일명용"],
  ["SameSite", "세임사이트", "쿠키를 다른 사이트 요청에 실을지"],
  ["Secure", "시큐어", "HTTPS 에서만 쿠키 전송"],
  ["HttpOnly", "에이치티티피 온리", "JS 에서 쿠키 접근 금지"],
  ["X-Forwarded-Proto", "엑스 포워디드 프로토", "원래 요청이 http 인지 https 인지"],
  ["X-Forwarded-For", "엑스 포워디드 포", "원래 클라이언트 IP 목록"],
  ["X-Real-IP", "엑스 리얼 아이피", "원래 클라이언트 IP 하나"],
  ["X-Request-Id", "엑스 리퀘스트 아이디", "요청 추적 ID 헤더"],
  ["Upgrade", "업그레이드", "프로토콜 전환 헤더 — 웹소켓"],
  ["Connection", "커넥션", "연결 유지·전환 헤더"],
  ["Connection refused", "커넥션 리퓨즈드", "그 주소·포트에 듣는 프로세스가 없음"],

  /* ── 리눅스 · 운영 ── */
  ["systemctl", "시스템씨티엘 / 시스템컨트롤", "systemd 서비스 제어"],
  ["journalctl", "저널씨티엘 / 저널컨트롤", "systemd 로그 보기"],
  ["LimitNOFILE", "리밋 노파일", "systemd — 열 수 있는 파일 수 상한"],
  ["SystemMaxUse", "시스템 맥스 유즈", "journald 로그 디스크 상한"],
  ["ulimit", "유리밋", "프로세스 자원 한도"],
  ["fs.file-max", "에프에스 닷 파일 맥스", "시스템 전체 파일 핸들 상한"],
  ["somaxconn", "소맥스콘", "listen 대기열 최대 길이"],
  ["backlog", "백로그", "accept 대기 큐 길이"],
  ["TIME_WAIT", "타임 웨이트", "닫힌 뒤 잠시 남는 TCP 상태"],
  ["tcp_tw_reuse", "티씨피 티더블유 리유즈", "TIME_WAIT 포트를 새 연결에 재사용"],
  ["copytruncate", "카피트렁케이트", "logrotate — 복사 후 원본 비우기"],
  ["rsyslog", "알시스로그", "시스로그 데몬"],
  ["ss", "에스에스", "소켓 상태 보기 — netstat 후속"],
  ["ss -tlnp", "에스에스 티엘엔피", "듣는 TCP 포트와 프로세스"],
  ["netstat", "넷스탯", "네트워크 연결 보기(구형)"],
  ["lsof", "엘에스오에프 / 엘솝", "열린 파일·소켓 목록"],
  ["curl", "컬", "HTTP 요청 도구"],
  ["dig", "디그", "DNS 조회"],
  ["sudo", "수도", "관리자 권한으로 실행"],
  ["chmod", "체모드 / 씨에이치모드", "권한 바꾸기"],
  ["www-data", "더블유더블유더블유 데이터", "데비안 계열 웹 서버 계정"],
  ["nologin", "노로그인", "로그인 셸 없는 계정"],
  ["restorecon", "리스토어콘", "SELinux 라벨 되돌리기"],
  ["setsebool", "셋에스이불", "SELinux 불린 값 켜기"],
  ["httpd_can_network_connect", "에이치티티피디 캔 네트워크 커넥트", "SELinux — 웹 서버의 바깥 연결 허용"],
  ["SIGTERM", "시그텀", "정상 종료 요청 신호"],
  ["USR1", "유에스알 원", "사용자 신호 1 — nginx 로그 파일 다시 열기"],
  ["kill", "킬", "프로세스에 신호 보내기"],
  ["Test-NetConnection", "테스트 넷커넥션", "PowerShell 포트 연결 확인"],

  /* ── 컨테이너 · k8s ── */
  ["docker", "도커", "컨테이너 도구"],
  ["compose", "컴포즈", "여러 컨테이너 정의·실행"],
  ["depends_on", "디펜즈 온", "compose — 시작 순서 의존"],
  ["healthcheck", "헬스체크", "컨테이너 상태 검사"],
  ["ENTRYPOINT", "엔트리포인트", "컨테이너 시작 명령"],
  ["kubectl", "큐브컨트롤 / 큐브씨티엘", "쿠버네티스 CLI"],
  ["rollout", "롤아웃", "배포 진행·되돌리기"],
  ["preStop", "프리스톱", "종료 직전 훅 — 트래픽 빠질 시간 벌기"],
  ["readinessProbe", "레디니스 프로브", "트래픽 받을 준비 검사"],
  ["maxUnavailable", "맥스 언어베일러블", "롤링 중 동시에 빠질 수 있는 수"],
  ["maxSurge", "맥스 서지", "롤링 중 더 띄울 수 있는 수"],
  ["Pending", "펜딩", "아직 노드에 못 올라간 Pod"],
  ["DiskPressure", "디스크 프레셔", "노드 디스크 부족 상태"],
  ["OOMKilled", "오오엠 킬드 / 움킬드", "메모리 한도 초과로 강제 종료"],
  ["ImagePullBackOff", "이미지 풀 백오프", "이미지 못 받아 재시도 대기"],
  ["kustomize", "커스터마이즈", "오버레이 방식 매니페스트 조립"],
  ["helm", "헬름", "쿠버네티스 패키지 관리자"],
  ["argocd", "아르고씨디", "GitOps 배포 도구"],

  /* ── 관측 ── */
  ["trace_id", "트레이스 아이디", "요청 하나를 잇는 추적 ID"],
  ["traceparent", "트레이스페어런트", "W3C 추적 전파 헤더"],
  ["prometheus", "프로메테우스", "지표 수집·저장"],
  ["histogram_quantile", "히스토그램 퀀타일", "PromQL — 백분위 계산(p99)"],
  ["predict_linear", "프레딕트 리니어", "PromQL — 추세로 미래 값 예측"],
  ["metric_relabel_configs", "메트릭 리레이블 컨피그스", "수집 뒤 라벨 정리·버리기"],

  /* ── 메시징 ── */
  ["acks=all", "액스 이퀄 올", "Kafka — 모든 ISR 복제 확인 후 성공"],
  ["min.insync.replicas", "민 인싱크 레플리카스", "Kafka — 최소 동기 복제본 수"],
  ["haproxy", "에이치에이프록시", "L4·L7 로드 밸런서"],
  ["max.poll.interval.ms", "맥스 폴 인터벌 밀리초", "Kafka — poll 간격이 이보다 길면 그룹에서 쫓겨남"],
  ["retention.ms", "리텐션 밀리초", "Kafka — 메시지 보관 기간"],
  ["cleanup.policy", "클린업 폴리시", "Kafka — delete 또는 compact"],
  ["exactly_once_v2", "이그잭틀리 원스 브이투", "Kafka Streams 정확히 한 번 처리"],
  ["DeadLetterPublishingRecoverer", "데드레터 퍼블리싱 리커버러", "스프링 카프카 — 실패 메시지를 DLT 로"],
  ["kafka-consumer-groups.sh", "카프카 컨슈머 그룹스", "컨슈머 그룹 lag 확인·오프셋 리셋"],

  /* ── 추가: 본문 인라인 토큰 ── */
  ["ssl_certificate", "에스에스엘 서티피킷", "nginx 인증서 경로"],
  ["ProxyPassReverse", "프록시 패스 리버스", "백엔드 리다이렉트 주소를 바깥 주소로 고침"],
  ["VirtualHost", "버추얼 호스트", "Apache 가상 호스트 블록"],
  ["DocumentRoot", "도큐먼트 루트", "Apache 문서 루트"],
  ["stub_status", "스텁 스테이터스", "nginx 연결 수 상태 페이지"],
  ["Strict-Transport-Security", "스트릭트 트랜스포트 시큐리티", "HSTS — 이 도메인은 HTTPS 로만"],
  ["Content-Security-Policy", "콘텐트 시큐리티 폴리시", "CSP — 불러올 수 있는 출처 제한"],
  ["X-Frame-Options", "엑스 프레임 옵션스", "iframe 삽입 금지 — 클릭재킹 방어"],
  ["nosniff", "노스니프", "MIME 추측 금지"],
  ["stale-while-revalidate", "스테일 와일 리밸리데이트", "옛 캐시를 주면서 뒤에서 갱신"],
  ["must-revalidate", "머스트 리밸리데이트", "만료되면 반드시 재검증"],
  ["daemon-reload", "데몬 리로드", "systemd 유닛 파일 다시 읽기"],
  ["ExecStart", "엑섹 스타트", "systemd — 실행 명령"],
  ["sysctl", "시스씨티엘 / 시스컨트롤", "커널 파라미터 보기·설정"],
  ["ip_local_port_range", "아이피 로컬 포트 레인지", "나가는 연결에 쓸 포트 범위"],
  ["tcp_tw_recycle", "티씨피 티더블유 리사이클", "NAT 뒤에서 연결 끊김 — 커널 4.12 에서 삭제"],
  ["io_uring", "아이오 유링", "리눅스 비동기 I/O 인터페이스"],
  ["kTLS", "케이티엘에스", "커널 TLS — sendfile 로 암호화 전송"],
  ["proxy_protocol", "프록시 프로토콜", "L4 로드 밸런서가 원래 IP 를 앞에 붙여 전달"],
  ["limit_conn", "리밋 콘", "동시 연결 수 제한"],
  ["burst", "버스트", "속도 제한에서 잠깐 허용할 초과량"],
  ["nodelay", "노딜레이", "burst 안의 요청을 지연 없이 바로 처리"],
  ["auth_basic", "어스 베이직", "nginx 기본 인증"],
  ["X-Accel-Redirect", "엑스 액셀 리다이렉트", "앱이 허락하고 파일 전송은 nginx 가"],
  ["worker_cpu_affinity", "워커 씨피유 어피니티", "워커를 특정 코어에 고정"],
  ["Http11NioProtocol", "에이치티티피 일일 엔아이오 프로토콜", "Tomcat NIO 커넥터"],
  ["RemoteIpValve", "리모트 아이피 밸브", "Tomcat — X-Forwarded-For 로 진짜 IP 복원"],
  ["Metaspace", "메타스페이스", "JVM 클래스 메타데이터 영역"],
  ["ActiveProcessorCount", "액티브 프로세서 카운트", "JVM 이 볼 CPU 수 지정"],
  ["GOMAXPROCS", "고맥스프록스", "Go 가 동시에 쓸 OS 스레드 수"],
  ["gevent", "지이벤트", "파이썬 그린스레드 라이브러리"],
  ["pm.max_children", "피엠 맥스 칠드런", "php-fpm 워커 상한"],
  ["NXDOMAIN", "엔엑스도메인", "DNS — 그런 이름 없음"],
  ["ECDHE", "이씨디에이치이", "타원곡선 임시 키 교환 — 순방향 보안"],
  ["SIGKILL", "시그킬", "즉시 강제 종료 신호 — 못 막음"],
  ["tini", "티니", "컨테이너용 작은 init — 신호 전달·좀비 회수"],
  ["podman", "파드맨", "데몬 없는 컨테이너 도구"],
  ["crictl", "크라이씨티엘", "CRI 런타임 디버그 CLI"],
  ["IfNotPresent", "이프 낫 프레즌트", "노드에 이미지가 없을 때만 받기"],
  ["terminationGracePeriodSeconds", "터미네이션 그레이스 피리어드 세컨즈", "SIGTERM 뒤 SIGKILL 까지 기다리는 시간"],
  ["LoadBalancer", "로드밸런서", "k8s Service 형식 — 클라우드 LB 생성"],
  ["targetPort", "타깃 포트", "Service 가 넘길 컨테이너 포트"],
  ["etcd", "엣시디 / 이티씨디", "k8s 상태 저장 키-값 저장소"],
  ["nodeSelector", "노드 셀렉터", "라벨로 올라갈 노드 고르기"],
  ["emptyDir", "엠티 디르", "Pod 수명 동안의 임시 볼륨"],
  ["ServiceMonitor", "서비스 모니터", "Prometheus Operator 수집 대상 정의"],
  ["OutOfSync", "아웃 오브 싱크", "Argo CD — Git 과 클러스터 상태가 다름"],
  ["selfHeal", "셀프 힐", "Argo CD — 손으로 바꾼 것을 Git 기준으로 되돌림"],
  ["sync-wave", "싱크 웨이브", "Argo CD 적용 순서"],
  ["relabel_configs", "리레이블 컨피그스", "수집 전 대상 라벨 정리"],
  ["scrape_interval", "스크레이프 인터벌", "지표 수집 주기"],
  ["topk", "탑케이", "PromQL — 상위 k 개"],
  ["http_requests_total", "에이치티티피 리퀘스츠 토털", "요청 수 카운터 — rate() 와 짝"],
  ["Retry-After", "리트라이 애프터", "다시 시도할 시점 헤더(429·503)"],
  ["Last-Event-ID", "라스트 이벤트 아이디", "SSE 재연결 때 마지막 받은 ID"],
  ["grpc_pass", "지알피씨 패스", "nginx gRPC 프록시"],
  ["mime.types", "마임 타입스", "확장자 → Content-Type 표"],
  ["autoindex", "오토인덱스", "폴더 목록 자동 표시 — 운영에선 끔"],
  ["FollowSymLinks", "팔로 심링크스", "Apache — 심볼릭 링크 따라가기 허용"],
  ["NODE_ENV", "노드 인브이 / 노드 env", "Node 실행 환경 — production"],
  ["PYTHONUNBUFFERED", "파이썬 언버퍼드", "출력을 버퍼 없이 — 컨테이너 로그 지연 방지"],
];
